// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: outbox/v1/channel.proto

package outboxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	outboxv1 "github.com/getoutbox/outbox-go/outboxv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChannelServiceName is the fully-qualified name of the ChannelService service.
	ChannelServiceName = "outbox.v1.ChannelService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChannelServiceGetChannelProcedure is the fully-qualified name of the ChannelService's GetChannel
	// RPC.
	ChannelServiceGetChannelProcedure = "/outbox.v1.ChannelService/GetChannel"
	// ChannelServiceListChannelsProcedure is the fully-qualified name of the ChannelService's
	// ListChannels RPC.
	ChannelServiceListChannelsProcedure = "/outbox.v1.ChannelService/ListChannels"
)

// ChannelServiceClient is a client for the outbox.v1.ChannelService service.
type ChannelServiceClient interface {
	GetChannel(context.Context, *connect.Request[outboxv1.GetChannelRequest]) (*connect.Response[outboxv1.GetChannelResponse], error)
	ListChannels(context.Context, *connect.Request[outboxv1.ListChannelsRequest]) (*connect.Response[outboxv1.ListChannelsResponse], error)
}

// NewChannelServiceClient constructs a client for the outbox.v1.ChannelService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChannelServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChannelServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	channelServiceMethods := outboxv1.File_outbox_v1_channel_proto.Services().ByName("ChannelService").Methods()
	return &channelServiceClient{
		getChannel: connect.NewClient[outboxv1.GetChannelRequest, outboxv1.GetChannelResponse](
			httpClient,
			baseURL+ChannelServiceGetChannelProcedure,
			connect.WithSchema(channelServiceMethods.ByName("GetChannel")),
			connect.WithClientOptions(opts...),
		),
		listChannels: connect.NewClient[outboxv1.ListChannelsRequest, outboxv1.ListChannelsResponse](
			httpClient,
			baseURL+ChannelServiceListChannelsProcedure,
			connect.WithSchema(channelServiceMethods.ByName("ListChannels")),
			connect.WithClientOptions(opts...),
		),
	}
}

// channelServiceClient implements ChannelServiceClient.
type channelServiceClient struct {
	getChannel   *connect.Client[outboxv1.GetChannelRequest, outboxv1.GetChannelResponse]
	listChannels *connect.Client[outboxv1.ListChannelsRequest, outboxv1.ListChannelsResponse]
}

// GetChannel calls outbox.v1.ChannelService.GetChannel.
func (c *channelServiceClient) GetChannel(ctx context.Context, req *connect.Request[outboxv1.GetChannelRequest]) (*connect.Response[outboxv1.GetChannelResponse], error) {
	return c.getChannel.CallUnary(ctx, req)
}

// ListChannels calls outbox.v1.ChannelService.ListChannels.
func (c *channelServiceClient) ListChannels(ctx context.Context, req *connect.Request[outboxv1.ListChannelsRequest]) (*connect.Response[outboxv1.ListChannelsResponse], error) {
	return c.listChannels.CallUnary(ctx, req)
}

// ChannelServiceHandler is an implementation of the outbox.v1.ChannelService service.
type ChannelServiceHandler interface {
	GetChannel(context.Context, *connect.Request[outboxv1.GetChannelRequest]) (*connect.Response[outboxv1.GetChannelResponse], error)
	ListChannels(context.Context, *connect.Request[outboxv1.ListChannelsRequest]) (*connect.Response[outboxv1.ListChannelsResponse], error)
}

// NewChannelServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChannelServiceHandler(svc ChannelServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	channelServiceMethods := outboxv1.File_outbox_v1_channel_proto.Services().ByName("ChannelService").Methods()
	channelServiceGetChannelHandler := connect.NewUnaryHandler(
		ChannelServiceGetChannelProcedure,
		svc.GetChannel,
		connect.WithSchema(channelServiceMethods.ByName("GetChannel")),
		connect.WithHandlerOptions(opts...),
	)
	channelServiceListChannelsHandler := connect.NewUnaryHandler(
		ChannelServiceListChannelsProcedure,
		svc.ListChannels,
		connect.WithSchema(channelServiceMethods.ByName("ListChannels")),
		connect.WithHandlerOptions(opts...),
	)
	return "/outbox.v1.ChannelService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChannelServiceGetChannelProcedure:
			channelServiceGetChannelHandler.ServeHTTP(w, r)
		case ChannelServiceListChannelsProcedure:
			channelServiceListChannelsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChannelServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChannelServiceHandler struct{}

func (UnimplementedChannelServiceHandler) GetChannel(context.Context, *connect.Request[outboxv1.GetChannelRequest]) (*connect.Response[outboxv1.GetChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ChannelService.GetChannel is not implemented"))
}

func (UnimplementedChannelServiceHandler) ListChannels(context.Context, *connect.Request[outboxv1.ListChannelsRequest]) (*connect.Response[outboxv1.ListChannelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ChannelService.ListChannels is not implemented"))
}
