// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: outbox/v1/connector.proto

package outboxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	outboxv1 "github.com/getoutbox/outbox-go/outboxv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConnectorServiceName is the fully-qualified name of the ConnectorService service.
	ConnectorServiceName = "outbox.v1.ConnectorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConnectorServiceCreateConnectorProcedure is the fully-qualified name of the ConnectorService's
	// CreateConnector RPC.
	ConnectorServiceCreateConnectorProcedure = "/outbox.v1.ConnectorService/CreateConnector"
	// ConnectorServiceGetConnectorProcedure is the fully-qualified name of the ConnectorService's
	// GetConnector RPC.
	ConnectorServiceGetConnectorProcedure = "/outbox.v1.ConnectorService/GetConnector"
	// ConnectorServiceListConnectorsProcedure is the fully-qualified name of the ConnectorService's
	// ListConnectors RPC.
	ConnectorServiceListConnectorsProcedure = "/outbox.v1.ConnectorService/ListConnectors"
	// ConnectorServiceUpdateConnectorProcedure is the fully-qualified name of the ConnectorService's
	// UpdateConnector RPC.
	ConnectorServiceUpdateConnectorProcedure = "/outbox.v1.ConnectorService/UpdateConnector"
	// ConnectorServiceDeleteConnectorProcedure is the fully-qualified name of the ConnectorService's
	// DeleteConnector RPC.
	ConnectorServiceDeleteConnectorProcedure = "/outbox.v1.ConnectorService/DeleteConnector"
	// ConnectorServiceReauthorizeConnectorProcedure is the fully-qualified name of the
	// ConnectorService's ReauthorizeConnector RPC.
	ConnectorServiceReauthorizeConnectorProcedure = "/outbox.v1.ConnectorService/ReauthorizeConnector"
	// ConnectorServiceActivateConnectorProcedure is the fully-qualified name of the ConnectorService's
	// ActivateConnector RPC.
	ConnectorServiceActivateConnectorProcedure = "/outbox.v1.ConnectorService/ActivateConnector"
	// ConnectorServiceDeactivateConnectorProcedure is the fully-qualified name of the
	// ConnectorService's DeactivateConnector RPC.
	ConnectorServiceDeactivateConnectorProcedure = "/outbox.v1.ConnectorService/DeactivateConnector"
)

// ConnectorServiceClient is a client for the outbox.v1.ConnectorService service.
type ConnectorServiceClient interface {
	CreateConnector(context.Context, *connect.Request[outboxv1.CreateConnectorRequest]) (*connect.Response[outboxv1.CreateConnectorResponse], error)
	GetConnector(context.Context, *connect.Request[outboxv1.GetConnectorRequest]) (*connect.Response[outboxv1.GetConnectorResponse], error)
	ListConnectors(context.Context, *connect.Request[outboxv1.ListConnectorsRequest]) (*connect.Response[outboxv1.ListConnectorsResponse], error)
	UpdateConnector(context.Context, *connect.Request[outboxv1.UpdateConnectorRequest]) (*connect.Response[outboxv1.UpdateConnectorResponse], error)
	DeleteConnector(context.Context, *connect.Request[outboxv1.DeleteConnectorRequest]) (*connect.Response[outboxv1.DeleteConnectorResponse], error)
	ReauthorizeConnector(context.Context, *connect.Request[outboxv1.ReauthorizeConnectorRequest]) (*connect.Response[outboxv1.ReauthorizeConnectorResponse], error)
	ActivateConnector(context.Context, *connect.Request[outboxv1.ActivateConnectorRequest]) (*connect.Response[outboxv1.ActivateConnectorResponse], error)
	DeactivateConnector(context.Context, *connect.Request[outboxv1.DeactivateConnectorRequest]) (*connect.Response[outboxv1.DeactivateConnectorResponse], error)
}

// NewConnectorServiceClient constructs a client for the outbox.v1.ConnectorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	connectorServiceMethods := outboxv1.File_outbox_v1_connector_proto.Services().ByName("ConnectorService").Methods()
	return &connectorServiceClient{
		createConnector: connect.NewClient[outboxv1.CreateConnectorRequest, outboxv1.CreateConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceCreateConnectorProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("CreateConnector")),
			connect.WithClientOptions(opts...),
		),
		getConnector: connect.NewClient[outboxv1.GetConnectorRequest, outboxv1.GetConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceGetConnectorProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("GetConnector")),
			connect.WithClientOptions(opts...),
		),
		listConnectors: connect.NewClient[outboxv1.ListConnectorsRequest, outboxv1.ListConnectorsResponse](
			httpClient,
			baseURL+ConnectorServiceListConnectorsProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("ListConnectors")),
			connect.WithClientOptions(opts...),
		),
		updateConnector: connect.NewClient[outboxv1.UpdateConnectorRequest, outboxv1.UpdateConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceUpdateConnectorProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("UpdateConnector")),
			connect.WithClientOptions(opts...),
		),
		deleteConnector: connect.NewClient[outboxv1.DeleteConnectorRequest, outboxv1.DeleteConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceDeleteConnectorProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("DeleteConnector")),
			connect.WithClientOptions(opts...),
		),
		reauthorizeConnector: connect.NewClient[outboxv1.ReauthorizeConnectorRequest, outboxv1.ReauthorizeConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceReauthorizeConnectorProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("ReauthorizeConnector")),
			connect.WithClientOptions(opts...),
		),
		activateConnector: connect.NewClient[outboxv1.ActivateConnectorRequest, outboxv1.ActivateConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceActivateConnectorProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("ActivateConnector")),
			connect.WithClientOptions(opts...),
		),
		deactivateConnector: connect.NewClient[outboxv1.DeactivateConnectorRequest, outboxv1.DeactivateConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceDeactivateConnectorProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("DeactivateConnector")),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectorServiceClient implements ConnectorServiceClient.
type connectorServiceClient struct {
	createConnector      *connect.Client[outboxv1.CreateConnectorRequest, outboxv1.CreateConnectorResponse]
	getConnector         *connect.Client[outboxv1.GetConnectorRequest, outboxv1.GetConnectorResponse]
	listConnectors       *connect.Client[outboxv1.ListConnectorsRequest, outboxv1.ListConnectorsResponse]
	updateConnector      *connect.Client[outboxv1.UpdateConnectorRequest, outboxv1.UpdateConnectorResponse]
	deleteConnector      *connect.Client[outboxv1.DeleteConnectorRequest, outboxv1.DeleteConnectorResponse]
	reauthorizeConnector *connect.Client[outboxv1.ReauthorizeConnectorRequest, outboxv1.ReauthorizeConnectorResponse]
	activateConnector    *connect.Client[outboxv1.ActivateConnectorRequest, outboxv1.ActivateConnectorResponse]
	deactivateConnector  *connect.Client[outboxv1.DeactivateConnectorRequest, outboxv1.DeactivateConnectorResponse]
}

// CreateConnector calls outbox.v1.ConnectorService.CreateConnector.
func (c *connectorServiceClient) CreateConnector(ctx context.Context, req *connect.Request[outboxv1.CreateConnectorRequest]) (*connect.Response[outboxv1.CreateConnectorResponse], error) {
	return c.createConnector.CallUnary(ctx, req)
}

// GetConnector calls outbox.v1.ConnectorService.GetConnector.
func (c *connectorServiceClient) GetConnector(ctx context.Context, req *connect.Request[outboxv1.GetConnectorRequest]) (*connect.Response[outboxv1.GetConnectorResponse], error) {
	return c.getConnector.CallUnary(ctx, req)
}

// ListConnectors calls outbox.v1.ConnectorService.ListConnectors.
func (c *connectorServiceClient) ListConnectors(ctx context.Context, req *connect.Request[outboxv1.ListConnectorsRequest]) (*connect.Response[outboxv1.ListConnectorsResponse], error) {
	return c.listConnectors.CallUnary(ctx, req)
}

// UpdateConnector calls outbox.v1.ConnectorService.UpdateConnector.
func (c *connectorServiceClient) UpdateConnector(ctx context.Context, req *connect.Request[outboxv1.UpdateConnectorRequest]) (*connect.Response[outboxv1.UpdateConnectorResponse], error) {
	return c.updateConnector.CallUnary(ctx, req)
}

// DeleteConnector calls outbox.v1.ConnectorService.DeleteConnector.
func (c *connectorServiceClient) DeleteConnector(ctx context.Context, req *connect.Request[outboxv1.DeleteConnectorRequest]) (*connect.Response[outboxv1.DeleteConnectorResponse], error) {
	return c.deleteConnector.CallUnary(ctx, req)
}

// ReauthorizeConnector calls outbox.v1.ConnectorService.ReauthorizeConnector.
func (c *connectorServiceClient) ReauthorizeConnector(ctx context.Context, req *connect.Request[outboxv1.ReauthorizeConnectorRequest]) (*connect.Response[outboxv1.ReauthorizeConnectorResponse], error) {
	return c.reauthorizeConnector.CallUnary(ctx, req)
}

// ActivateConnector calls outbox.v1.ConnectorService.ActivateConnector.
func (c *connectorServiceClient) ActivateConnector(ctx context.Context, req *connect.Request[outboxv1.ActivateConnectorRequest]) (*connect.Response[outboxv1.ActivateConnectorResponse], error) {
	return c.activateConnector.CallUnary(ctx, req)
}

// DeactivateConnector calls outbox.v1.ConnectorService.DeactivateConnector.
func (c *connectorServiceClient) DeactivateConnector(ctx context.Context, req *connect.Request[outboxv1.DeactivateConnectorRequest]) (*connect.Response[outboxv1.DeactivateConnectorResponse], error) {
	return c.deactivateConnector.CallUnary(ctx, req)
}

// ConnectorServiceHandler is an implementation of the outbox.v1.ConnectorService service.
type ConnectorServiceHandler interface {
	CreateConnector(context.Context, *connect.Request[outboxv1.CreateConnectorRequest]) (*connect.Response[outboxv1.CreateConnectorResponse], error)
	GetConnector(context.Context, *connect.Request[outboxv1.GetConnectorRequest]) (*connect.Response[outboxv1.GetConnectorResponse], error)
	ListConnectors(context.Context, *connect.Request[outboxv1.ListConnectorsRequest]) (*connect.Response[outboxv1.ListConnectorsResponse], error)
	UpdateConnector(context.Context, *connect.Request[outboxv1.UpdateConnectorRequest]) (*connect.Response[outboxv1.UpdateConnectorResponse], error)
	DeleteConnector(context.Context, *connect.Request[outboxv1.DeleteConnectorRequest]) (*connect.Response[outboxv1.DeleteConnectorResponse], error)
	ReauthorizeConnector(context.Context, *connect.Request[outboxv1.ReauthorizeConnectorRequest]) (*connect.Response[outboxv1.ReauthorizeConnectorResponse], error)
	ActivateConnector(context.Context, *connect.Request[outboxv1.ActivateConnectorRequest]) (*connect.Response[outboxv1.ActivateConnectorResponse], error)
	DeactivateConnector(context.Context, *connect.Request[outboxv1.DeactivateConnectorRequest]) (*connect.Response[outboxv1.DeactivateConnectorResponse], error)
}

// NewConnectorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectorServiceHandler(svc ConnectorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectorServiceMethods := outboxv1.File_outbox_v1_connector_proto.Services().ByName("ConnectorService").Methods()
	connectorServiceCreateConnectorHandler := connect.NewUnaryHandler(
		ConnectorServiceCreateConnectorProcedure,
		svc.CreateConnector,
		connect.WithSchema(connectorServiceMethods.ByName("CreateConnector")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceGetConnectorHandler := connect.NewUnaryHandler(
		ConnectorServiceGetConnectorProcedure,
		svc.GetConnector,
		connect.WithSchema(connectorServiceMethods.ByName("GetConnector")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceListConnectorsHandler := connect.NewUnaryHandler(
		ConnectorServiceListConnectorsProcedure,
		svc.ListConnectors,
		connect.WithSchema(connectorServiceMethods.ByName("ListConnectors")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceUpdateConnectorHandler := connect.NewUnaryHandler(
		ConnectorServiceUpdateConnectorProcedure,
		svc.UpdateConnector,
		connect.WithSchema(connectorServiceMethods.ByName("UpdateConnector")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceDeleteConnectorHandler := connect.NewUnaryHandler(
		ConnectorServiceDeleteConnectorProcedure,
		svc.DeleteConnector,
		connect.WithSchema(connectorServiceMethods.ByName("DeleteConnector")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceReauthorizeConnectorHandler := connect.NewUnaryHandler(
		ConnectorServiceReauthorizeConnectorProcedure,
		svc.ReauthorizeConnector,
		connect.WithSchema(connectorServiceMethods.ByName("ReauthorizeConnector")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceActivateConnectorHandler := connect.NewUnaryHandler(
		ConnectorServiceActivateConnectorProcedure,
		svc.ActivateConnector,
		connect.WithSchema(connectorServiceMethods.ByName("ActivateConnector")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceDeactivateConnectorHandler := connect.NewUnaryHandler(
		ConnectorServiceDeactivateConnectorProcedure,
		svc.DeactivateConnector,
		connect.WithSchema(connectorServiceMethods.ByName("DeactivateConnector")),
		connect.WithHandlerOptions(opts...),
	)
	return "/outbox.v1.ConnectorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectorServiceCreateConnectorProcedure:
			connectorServiceCreateConnectorHandler.ServeHTTP(w, r)
		case ConnectorServiceGetConnectorProcedure:
			connectorServiceGetConnectorHandler.ServeHTTP(w, r)
		case ConnectorServiceListConnectorsProcedure:
			connectorServiceListConnectorsHandler.ServeHTTP(w, r)
		case ConnectorServiceUpdateConnectorProcedure:
			connectorServiceUpdateConnectorHandler.ServeHTTP(w, r)
		case ConnectorServiceDeleteConnectorProcedure:
			connectorServiceDeleteConnectorHandler.ServeHTTP(w, r)
		case ConnectorServiceReauthorizeConnectorProcedure:
			connectorServiceReauthorizeConnectorHandler.ServeHTTP(w, r)
		case ConnectorServiceActivateConnectorProcedure:
			connectorServiceActivateConnectorHandler.ServeHTTP(w, r)
		case ConnectorServiceDeactivateConnectorProcedure:
			connectorServiceDeactivateConnectorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectorServiceHandler struct{}

func (UnimplementedConnectorServiceHandler) CreateConnector(context.Context, *connect.Request[outboxv1.CreateConnectorRequest]) (*connect.Response[outboxv1.CreateConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ConnectorService.CreateConnector is not implemented"))
}

func (UnimplementedConnectorServiceHandler) GetConnector(context.Context, *connect.Request[outboxv1.GetConnectorRequest]) (*connect.Response[outboxv1.GetConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ConnectorService.GetConnector is not implemented"))
}

func (UnimplementedConnectorServiceHandler) ListConnectors(context.Context, *connect.Request[outboxv1.ListConnectorsRequest]) (*connect.Response[outboxv1.ListConnectorsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ConnectorService.ListConnectors is not implemented"))
}

func (UnimplementedConnectorServiceHandler) UpdateConnector(context.Context, *connect.Request[outboxv1.UpdateConnectorRequest]) (*connect.Response[outboxv1.UpdateConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ConnectorService.UpdateConnector is not implemented"))
}

func (UnimplementedConnectorServiceHandler) DeleteConnector(context.Context, *connect.Request[outboxv1.DeleteConnectorRequest]) (*connect.Response[outboxv1.DeleteConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ConnectorService.DeleteConnector is not implemented"))
}

func (UnimplementedConnectorServiceHandler) ReauthorizeConnector(context.Context, *connect.Request[outboxv1.ReauthorizeConnectorRequest]) (*connect.Response[outboxv1.ReauthorizeConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ConnectorService.ReauthorizeConnector is not implemented"))
}

func (UnimplementedConnectorServiceHandler) ActivateConnector(context.Context, *connect.Request[outboxv1.ActivateConnectorRequest]) (*connect.Response[outboxv1.ActivateConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ConnectorService.ActivateConnector is not implemented"))
}

func (UnimplementedConnectorServiceHandler) DeactivateConnector(context.Context, *connect.Request[outboxv1.DeactivateConnectorRequest]) (*connect.Response[outboxv1.DeactivateConnectorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.ConnectorService.DeactivateConnector is not implemented"))
}
