// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: outbox/v1/destination.proto

package outboxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	outboxv1 "github.com/getoutbox/outbox-go/outboxv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DestinationServiceName is the fully-qualified name of the DestinationService service.
	DestinationServiceName = "outbox.v1.DestinationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DestinationServiceCreateDestinationProcedure is the fully-qualified name of the
	// DestinationService's CreateDestination RPC.
	DestinationServiceCreateDestinationProcedure = "/outbox.v1.DestinationService/CreateDestination"
	// DestinationServiceGetDestinationProcedure is the fully-qualified name of the DestinationService's
	// GetDestination RPC.
	DestinationServiceGetDestinationProcedure = "/outbox.v1.DestinationService/GetDestination"
	// DestinationServiceListDestinationsProcedure is the fully-qualified name of the
	// DestinationService's ListDestinations RPC.
	DestinationServiceListDestinationsProcedure = "/outbox.v1.DestinationService/ListDestinations"
	// DestinationServiceUpdateDestinationProcedure is the fully-qualified name of the
	// DestinationService's UpdateDestination RPC.
	DestinationServiceUpdateDestinationProcedure = "/outbox.v1.DestinationService/UpdateDestination"
	// DestinationServiceDeleteDestinationProcedure is the fully-qualified name of the
	// DestinationService's DeleteDestination RPC.
	DestinationServiceDeleteDestinationProcedure = "/outbox.v1.DestinationService/DeleteDestination"
	// DestinationServiceTestDestinationProcedure is the fully-qualified name of the
	// DestinationService's TestDestination RPC.
	DestinationServiceTestDestinationProcedure = "/outbox.v1.DestinationService/TestDestination"
	// DestinationServiceListDestinationTestResultsProcedure is the fully-qualified name of the
	// DestinationService's ListDestinationTestResults RPC.
	DestinationServiceListDestinationTestResultsProcedure = "/outbox.v1.DestinationService/ListDestinationTestResults"
	// DestinationServiceValidateDestinationFilterProcedure is the fully-qualified name of the
	// DestinationService's ValidateDestinationFilter RPC.
	DestinationServiceValidateDestinationFilterProcedure = "/outbox.v1.DestinationService/ValidateDestinationFilter"
	// DestinationServicePollEventsProcedure is the fully-qualified name of the DestinationService's
	// PollEvents RPC.
	DestinationServicePollEventsProcedure = "/outbox.v1.DestinationService/PollEvents"
)

// DestinationServiceClient is a client for the outbox.v1.DestinationService service.
type DestinationServiceClient interface {
	CreateDestination(context.Context, *connect.Request[outboxv1.CreateDestinationRequest]) (*connect.Response[outboxv1.CreateDestinationResponse], error)
	GetDestination(context.Context, *connect.Request[outboxv1.GetDestinationRequest]) (*connect.Response[outboxv1.GetDestinationResponse], error)
	ListDestinations(context.Context, *connect.Request[outboxv1.ListDestinationsRequest]) (*connect.Response[outboxv1.ListDestinationsResponse], error)
	UpdateDestination(context.Context, *connect.Request[outboxv1.UpdateDestinationRequest]) (*connect.Response[outboxv1.UpdateDestinationResponse], error)
	DeleteDestination(context.Context, *connect.Request[outboxv1.DeleteDestinationRequest]) (*connect.Response[outboxv1.DeleteDestinationResponse], error)
	TestDestination(context.Context, *connect.Request[outboxv1.TestDestinationRequest]) (*connect.Response[outboxv1.TestDestinationResponse], error)
	ListDestinationTestResults(context.Context, *connect.Request[outboxv1.ListDestinationTestResultsRequest]) (*connect.Response[outboxv1.ListDestinationTestResultsResponse], error)
	ValidateDestinationFilter(context.Context, *connect.Request[outboxv1.ValidateDestinationFilterRequest]) (*connect.Response[outboxv1.ValidateDestinationFilterResponse], error)
	PollEvents(context.Context, *connect.Request[outboxv1.PollEventsRequest]) (*connect.Response[outboxv1.PollEventsResponse], error)
}

// NewDestinationServiceClient constructs a client for the outbox.v1.DestinationService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDestinationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DestinationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	destinationServiceMethods := outboxv1.File_outbox_v1_destination_proto.Services().ByName("DestinationService").Methods()
	return &destinationServiceClient{
		createDestination: connect.NewClient[outboxv1.CreateDestinationRequest, outboxv1.CreateDestinationResponse](
			httpClient,
			baseURL+DestinationServiceCreateDestinationProcedure,
			connect.WithSchema(destinationServiceMethods.ByName("CreateDestination")),
			connect.WithClientOptions(opts...),
		),
		getDestination: connect.NewClient[outboxv1.GetDestinationRequest, outboxv1.GetDestinationResponse](
			httpClient,
			baseURL+DestinationServiceGetDestinationProcedure,
			connect.WithSchema(destinationServiceMethods.ByName("GetDestination")),
			connect.WithClientOptions(opts...),
		),
		listDestinations: connect.NewClient[outboxv1.ListDestinationsRequest, outboxv1.ListDestinationsResponse](
			httpClient,
			baseURL+DestinationServiceListDestinationsProcedure,
			connect.WithSchema(destinationServiceMethods.ByName("ListDestinations")),
			connect.WithClientOptions(opts...),
		),
		updateDestination: connect.NewClient[outboxv1.UpdateDestinationRequest, outboxv1.UpdateDestinationResponse](
			httpClient,
			baseURL+DestinationServiceUpdateDestinationProcedure,
			connect.WithSchema(destinationServiceMethods.ByName("UpdateDestination")),
			connect.WithClientOptions(opts...),
		),
		deleteDestination: connect.NewClient[outboxv1.DeleteDestinationRequest, outboxv1.DeleteDestinationResponse](
			httpClient,
			baseURL+DestinationServiceDeleteDestinationProcedure,
			connect.WithSchema(destinationServiceMethods.ByName("DeleteDestination")),
			connect.WithClientOptions(opts...),
		),
		testDestination: connect.NewClient[outboxv1.TestDestinationRequest, outboxv1.TestDestinationResponse](
			httpClient,
			baseURL+DestinationServiceTestDestinationProcedure,
			connect.WithSchema(destinationServiceMethods.ByName("TestDestination")),
			connect.WithClientOptions(opts...),
		),
		listDestinationTestResults: connect.NewClient[outboxv1.ListDestinationTestResultsRequest, outboxv1.ListDestinationTestResultsResponse](
			httpClient,
			baseURL+DestinationServiceListDestinationTestResultsProcedure,
			connect.WithSchema(destinationServiceMethods.ByName("ListDestinationTestResults")),
			connect.WithClientOptions(opts...),
		),
		validateDestinationFilter: connect.NewClient[outboxv1.ValidateDestinationFilterRequest, outboxv1.ValidateDestinationFilterResponse](
			httpClient,
			baseURL+DestinationServiceValidateDestinationFilterProcedure,
			connect.WithSchema(destinationServiceMethods.ByName("ValidateDestinationFilter")),
			connect.WithClientOptions(opts...),
		),
		pollEvents: connect.NewClient[outboxv1.PollEventsRequest, outboxv1.PollEventsResponse](
			httpClient,
			baseURL+DestinationServicePollEventsProcedure,
			connect.WithSchema(destinationServiceMethods.ByName("PollEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// destinationServiceClient implements DestinationServiceClient.
type destinationServiceClient struct {
	createDestination          *connect.Client[outboxv1.CreateDestinationRequest, outboxv1.CreateDestinationResponse]
	getDestination             *connect.Client[outboxv1.GetDestinationRequest, outboxv1.GetDestinationResponse]
	listDestinations           *connect.Client[outboxv1.ListDestinationsRequest, outboxv1.ListDestinationsResponse]
	updateDestination          *connect.Client[outboxv1.UpdateDestinationRequest, outboxv1.UpdateDestinationResponse]
	deleteDestination          *connect.Client[outboxv1.DeleteDestinationRequest, outboxv1.DeleteDestinationResponse]
	testDestination            *connect.Client[outboxv1.TestDestinationRequest, outboxv1.TestDestinationResponse]
	listDestinationTestResults *connect.Client[outboxv1.ListDestinationTestResultsRequest, outboxv1.ListDestinationTestResultsResponse]
	validateDestinationFilter  *connect.Client[outboxv1.ValidateDestinationFilterRequest, outboxv1.ValidateDestinationFilterResponse]
	pollEvents                 *connect.Client[outboxv1.PollEventsRequest, outboxv1.PollEventsResponse]
}

// CreateDestination calls outbox.v1.DestinationService.CreateDestination.
func (c *destinationServiceClient) CreateDestination(ctx context.Context, req *connect.Request[outboxv1.CreateDestinationRequest]) (*connect.Response[outboxv1.CreateDestinationResponse], error) {
	return c.createDestination.CallUnary(ctx, req)
}

// GetDestination calls outbox.v1.DestinationService.GetDestination.
func (c *destinationServiceClient) GetDestination(ctx context.Context, req *connect.Request[outboxv1.GetDestinationRequest]) (*connect.Response[outboxv1.GetDestinationResponse], error) {
	return c.getDestination.CallUnary(ctx, req)
}

// ListDestinations calls outbox.v1.DestinationService.ListDestinations.
func (c *destinationServiceClient) ListDestinations(ctx context.Context, req *connect.Request[outboxv1.ListDestinationsRequest]) (*connect.Response[outboxv1.ListDestinationsResponse], error) {
	return c.listDestinations.CallUnary(ctx, req)
}

// UpdateDestination calls outbox.v1.DestinationService.UpdateDestination.
func (c *destinationServiceClient) UpdateDestination(ctx context.Context, req *connect.Request[outboxv1.UpdateDestinationRequest]) (*connect.Response[outboxv1.UpdateDestinationResponse], error) {
	return c.updateDestination.CallUnary(ctx, req)
}

// DeleteDestination calls outbox.v1.DestinationService.DeleteDestination.
func (c *destinationServiceClient) DeleteDestination(ctx context.Context, req *connect.Request[outboxv1.DeleteDestinationRequest]) (*connect.Response[outboxv1.DeleteDestinationResponse], error) {
	return c.deleteDestination.CallUnary(ctx, req)
}

// TestDestination calls outbox.v1.DestinationService.TestDestination.
func (c *destinationServiceClient) TestDestination(ctx context.Context, req *connect.Request[outboxv1.TestDestinationRequest]) (*connect.Response[outboxv1.TestDestinationResponse], error) {
	return c.testDestination.CallUnary(ctx, req)
}

// ListDestinationTestResults calls outbox.v1.DestinationService.ListDestinationTestResults.
func (c *destinationServiceClient) ListDestinationTestResults(ctx context.Context, req *connect.Request[outboxv1.ListDestinationTestResultsRequest]) (*connect.Response[outboxv1.ListDestinationTestResultsResponse], error) {
	return c.listDestinationTestResults.CallUnary(ctx, req)
}

// ValidateDestinationFilter calls outbox.v1.DestinationService.ValidateDestinationFilter.
func (c *destinationServiceClient) ValidateDestinationFilter(ctx context.Context, req *connect.Request[outboxv1.ValidateDestinationFilterRequest]) (*connect.Response[outboxv1.ValidateDestinationFilterResponse], error) {
	return c.validateDestinationFilter.CallUnary(ctx, req)
}

// PollEvents calls outbox.v1.DestinationService.PollEvents.
func (c *destinationServiceClient) PollEvents(ctx context.Context, req *connect.Request[outboxv1.PollEventsRequest]) (*connect.Response[outboxv1.PollEventsResponse], error) {
	return c.pollEvents.CallUnary(ctx, req)
}

// DestinationServiceHandler is an implementation of the outbox.v1.DestinationService service.
type DestinationServiceHandler interface {
	CreateDestination(context.Context, *connect.Request[outboxv1.CreateDestinationRequest]) (*connect.Response[outboxv1.CreateDestinationResponse], error)
	GetDestination(context.Context, *connect.Request[outboxv1.GetDestinationRequest]) (*connect.Response[outboxv1.GetDestinationResponse], error)
	ListDestinations(context.Context, *connect.Request[outboxv1.ListDestinationsRequest]) (*connect.Response[outboxv1.ListDestinationsResponse], error)
	UpdateDestination(context.Context, *connect.Request[outboxv1.UpdateDestinationRequest]) (*connect.Response[outboxv1.UpdateDestinationResponse], error)
	DeleteDestination(context.Context, *connect.Request[outboxv1.DeleteDestinationRequest]) (*connect.Response[outboxv1.DeleteDestinationResponse], error)
	TestDestination(context.Context, *connect.Request[outboxv1.TestDestinationRequest]) (*connect.Response[outboxv1.TestDestinationResponse], error)
	ListDestinationTestResults(context.Context, *connect.Request[outboxv1.ListDestinationTestResultsRequest]) (*connect.Response[outboxv1.ListDestinationTestResultsResponse], error)
	ValidateDestinationFilter(context.Context, *connect.Request[outboxv1.ValidateDestinationFilterRequest]) (*connect.Response[outboxv1.ValidateDestinationFilterResponse], error)
	PollEvents(context.Context, *connect.Request[outboxv1.PollEventsRequest]) (*connect.Response[outboxv1.PollEventsResponse], error)
}

// NewDestinationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDestinationServiceHandler(svc DestinationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	destinationServiceMethods := outboxv1.File_outbox_v1_destination_proto.Services().ByName("DestinationService").Methods()
	destinationServiceCreateDestinationHandler := connect.NewUnaryHandler(
		DestinationServiceCreateDestinationProcedure,
		svc.CreateDestination,
		connect.WithSchema(destinationServiceMethods.ByName("CreateDestination")),
		connect.WithHandlerOptions(opts...),
	)
	destinationServiceGetDestinationHandler := connect.NewUnaryHandler(
		DestinationServiceGetDestinationProcedure,
		svc.GetDestination,
		connect.WithSchema(destinationServiceMethods.ByName("GetDestination")),
		connect.WithHandlerOptions(opts...),
	)
	destinationServiceListDestinationsHandler := connect.NewUnaryHandler(
		DestinationServiceListDestinationsProcedure,
		svc.ListDestinations,
		connect.WithSchema(destinationServiceMethods.ByName("ListDestinations")),
		connect.WithHandlerOptions(opts...),
	)
	destinationServiceUpdateDestinationHandler := connect.NewUnaryHandler(
		DestinationServiceUpdateDestinationProcedure,
		svc.UpdateDestination,
		connect.WithSchema(destinationServiceMethods.ByName("UpdateDestination")),
		connect.WithHandlerOptions(opts...),
	)
	destinationServiceDeleteDestinationHandler := connect.NewUnaryHandler(
		DestinationServiceDeleteDestinationProcedure,
		svc.DeleteDestination,
		connect.WithSchema(destinationServiceMethods.ByName("DeleteDestination")),
		connect.WithHandlerOptions(opts...),
	)
	destinationServiceTestDestinationHandler := connect.NewUnaryHandler(
		DestinationServiceTestDestinationProcedure,
		svc.TestDestination,
		connect.WithSchema(destinationServiceMethods.ByName("TestDestination")),
		connect.WithHandlerOptions(opts...),
	)
	destinationServiceListDestinationTestResultsHandler := connect.NewUnaryHandler(
		DestinationServiceListDestinationTestResultsProcedure,
		svc.ListDestinationTestResults,
		connect.WithSchema(destinationServiceMethods.ByName("ListDestinationTestResults")),
		connect.WithHandlerOptions(opts...),
	)
	destinationServiceValidateDestinationFilterHandler := connect.NewUnaryHandler(
		DestinationServiceValidateDestinationFilterProcedure,
		svc.ValidateDestinationFilter,
		connect.WithSchema(destinationServiceMethods.ByName("ValidateDestinationFilter")),
		connect.WithHandlerOptions(opts...),
	)
	destinationServicePollEventsHandler := connect.NewUnaryHandler(
		DestinationServicePollEventsProcedure,
		svc.PollEvents,
		connect.WithSchema(destinationServiceMethods.ByName("PollEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/outbox.v1.DestinationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DestinationServiceCreateDestinationProcedure:
			destinationServiceCreateDestinationHandler.ServeHTTP(w, r)
		case DestinationServiceGetDestinationProcedure:
			destinationServiceGetDestinationHandler.ServeHTTP(w, r)
		case DestinationServiceListDestinationsProcedure:
			destinationServiceListDestinationsHandler.ServeHTTP(w, r)
		case DestinationServiceUpdateDestinationProcedure:
			destinationServiceUpdateDestinationHandler.ServeHTTP(w, r)
		case DestinationServiceDeleteDestinationProcedure:
			destinationServiceDeleteDestinationHandler.ServeHTTP(w, r)
		case DestinationServiceTestDestinationProcedure:
			destinationServiceTestDestinationHandler.ServeHTTP(w, r)
		case DestinationServiceListDestinationTestResultsProcedure:
			destinationServiceListDestinationTestResultsHandler.ServeHTTP(w, r)
		case DestinationServiceValidateDestinationFilterProcedure:
			destinationServiceValidateDestinationFilterHandler.ServeHTTP(w, r)
		case DestinationServicePollEventsProcedure:
			destinationServicePollEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDestinationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDestinationServiceHandler struct{}

func (UnimplementedDestinationServiceHandler) CreateDestination(context.Context, *connect.Request[outboxv1.CreateDestinationRequest]) (*connect.Response[outboxv1.CreateDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.DestinationService.CreateDestination is not implemented"))
}

func (UnimplementedDestinationServiceHandler) GetDestination(context.Context, *connect.Request[outboxv1.GetDestinationRequest]) (*connect.Response[outboxv1.GetDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.DestinationService.GetDestination is not implemented"))
}

func (UnimplementedDestinationServiceHandler) ListDestinations(context.Context, *connect.Request[outboxv1.ListDestinationsRequest]) (*connect.Response[outboxv1.ListDestinationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.DestinationService.ListDestinations is not implemented"))
}

func (UnimplementedDestinationServiceHandler) UpdateDestination(context.Context, *connect.Request[outboxv1.UpdateDestinationRequest]) (*connect.Response[outboxv1.UpdateDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.DestinationService.UpdateDestination is not implemented"))
}

func (UnimplementedDestinationServiceHandler) DeleteDestination(context.Context, *connect.Request[outboxv1.DeleteDestinationRequest]) (*connect.Response[outboxv1.DeleteDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.DestinationService.DeleteDestination is not implemented"))
}

func (UnimplementedDestinationServiceHandler) TestDestination(context.Context, *connect.Request[outboxv1.TestDestinationRequest]) (*connect.Response[outboxv1.TestDestinationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.DestinationService.TestDestination is not implemented"))
}

func (UnimplementedDestinationServiceHandler) ListDestinationTestResults(context.Context, *connect.Request[outboxv1.ListDestinationTestResultsRequest]) (*connect.Response[outboxv1.ListDestinationTestResultsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.DestinationService.ListDestinationTestResults is not implemented"))
}

func (UnimplementedDestinationServiceHandler) ValidateDestinationFilter(context.Context, *connect.Request[outboxv1.ValidateDestinationFilterRequest]) (*connect.Response[outboxv1.ValidateDestinationFilterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.DestinationService.ValidateDestinationFilter is not implemented"))
}

func (UnimplementedDestinationServiceHandler) PollEvents(context.Context, *connect.Request[outboxv1.PollEventsRequest]) (*connect.Response[outboxv1.PollEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.DestinationService.PollEvents is not implemented"))
}
