// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: outbox/v1/message.proto

package outboxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	outboxv1 "github.com/getoutbox/outbox-go/outboxv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MessageServiceName is the fully-qualified name of the MessageService service.
	MessageServiceName = "outbox.v1.MessageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MessageServiceCreateMessageProcedure is the fully-qualified name of the MessageService's
	// CreateMessage RPC.
	MessageServiceCreateMessageProcedure = "/outbox.v1.MessageService/CreateMessage"
	// MessageServiceUpdateMessageProcedure is the fully-qualified name of the MessageService's
	// UpdateMessage RPC.
	MessageServiceUpdateMessageProcedure = "/outbox.v1.MessageService/UpdateMessage"
	// MessageServiceDeleteMessageProcedure is the fully-qualified name of the MessageService's
	// DeleteMessage RPC.
	MessageServiceDeleteMessageProcedure = "/outbox.v1.MessageService/DeleteMessage"
	// MessageServiceListMessagesProcedure is the fully-qualified name of the MessageService's
	// ListMessages RPC.
	MessageServiceListMessagesProcedure = "/outbox.v1.MessageService/ListMessages"
	// MessageServiceSendReadReceiptProcedure is the fully-qualified name of the MessageService's
	// SendReadReceipt RPC.
	MessageServiceSendReadReceiptProcedure = "/outbox.v1.MessageService/SendReadReceipt"
	// MessageServiceSendTypingIndicatorProcedure is the fully-qualified name of the MessageService's
	// SendTypingIndicator RPC.
	MessageServiceSendTypingIndicatorProcedure = "/outbox.v1.MessageService/SendTypingIndicator"
)

// MessageServiceClient is a client for the outbox.v1.MessageService service.
type MessageServiceClient interface {
	// Creates and sends a message. Also used for reactions (set reply_to
	// and parts[0].disposition = REACTION) and edits (set replaced).
	CreateMessage(context.Context, *connect.Request[outboxv1.CreateMessageRequest]) (*connect.Response[outboxv1.CreateMessageResponse], error)
	// Updates (edits) a previously sent message's content.
	UpdateMessage(context.Context, *connect.Request[outboxv1.UpdateMessageRequest]) (*connect.Response[outboxv1.UpdateMessageResponse], error)
	// Deletes a message. Returns the updated message with delete_time set.
	DeleteMessage(context.Context, *connect.Request[outboxv1.DeleteMessageRequest]) (*connect.Response[outboxv1.DeleteMessageResponse], error)
	ListMessages(context.Context, *connect.Request[outboxv1.ListMessagesRequest]) (*connect.Response[outboxv1.ListMessagesResponse], error)
	SendReadReceipt(context.Context, *connect.Request[outboxv1.SendReadReceiptRequest]) (*connect.Response[outboxv1.SendReadReceiptResponse], error)
	SendTypingIndicator(context.Context, *connect.Request[outboxv1.SendTypingIndicatorRequest]) (*connect.Response[outboxv1.SendTypingIndicatorResponse], error)
}

// NewMessageServiceClient constructs a client for the outbox.v1.MessageService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMessageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MessageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	messageServiceMethods := outboxv1.File_outbox_v1_message_proto.Services().ByName("MessageService").Methods()
	return &messageServiceClient{
		createMessage: connect.NewClient[outboxv1.CreateMessageRequest, outboxv1.CreateMessageResponse](
			httpClient,
			baseURL+MessageServiceCreateMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("CreateMessage")),
			connect.WithClientOptions(opts...),
		),
		updateMessage: connect.NewClient[outboxv1.UpdateMessageRequest, outboxv1.UpdateMessageResponse](
			httpClient,
			baseURL+MessageServiceUpdateMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("UpdateMessage")),
			connect.WithClientOptions(opts...),
		),
		deleteMessage: connect.NewClient[outboxv1.DeleteMessageRequest, outboxv1.DeleteMessageResponse](
			httpClient,
			baseURL+MessageServiceDeleteMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("DeleteMessage")),
			connect.WithClientOptions(opts...),
		),
		listMessages: connect.NewClient[outboxv1.ListMessagesRequest, outboxv1.ListMessagesResponse](
			httpClient,
			baseURL+MessageServiceListMessagesProcedure,
			connect.WithSchema(messageServiceMethods.ByName("ListMessages")),
			connect.WithClientOptions(opts...),
		),
		sendReadReceipt: connect.NewClient[outboxv1.SendReadReceiptRequest, outboxv1.SendReadReceiptResponse](
			httpClient,
			baseURL+MessageServiceSendReadReceiptProcedure,
			connect.WithSchema(messageServiceMethods.ByName("SendReadReceipt")),
			connect.WithClientOptions(opts...),
		),
		sendTypingIndicator: connect.NewClient[outboxv1.SendTypingIndicatorRequest, outboxv1.SendTypingIndicatorResponse](
			httpClient,
			baseURL+MessageServiceSendTypingIndicatorProcedure,
			connect.WithSchema(messageServiceMethods.ByName("SendTypingIndicator")),
			connect.WithClientOptions(opts...),
		),
	}
}

// messageServiceClient implements MessageServiceClient.
type messageServiceClient struct {
	createMessage       *connect.Client[outboxv1.CreateMessageRequest, outboxv1.CreateMessageResponse]
	updateMessage       *connect.Client[outboxv1.UpdateMessageRequest, outboxv1.UpdateMessageResponse]
	deleteMessage       *connect.Client[outboxv1.DeleteMessageRequest, outboxv1.DeleteMessageResponse]
	listMessages        *connect.Client[outboxv1.ListMessagesRequest, outboxv1.ListMessagesResponse]
	sendReadReceipt     *connect.Client[outboxv1.SendReadReceiptRequest, outboxv1.SendReadReceiptResponse]
	sendTypingIndicator *connect.Client[outboxv1.SendTypingIndicatorRequest, outboxv1.SendTypingIndicatorResponse]
}

// CreateMessage calls outbox.v1.MessageService.CreateMessage.
func (c *messageServiceClient) CreateMessage(ctx context.Context, req *connect.Request[outboxv1.CreateMessageRequest]) (*connect.Response[outboxv1.CreateMessageResponse], error) {
	return c.createMessage.CallUnary(ctx, req)
}

// UpdateMessage calls outbox.v1.MessageService.UpdateMessage.
func (c *messageServiceClient) UpdateMessage(ctx context.Context, req *connect.Request[outboxv1.UpdateMessageRequest]) (*connect.Response[outboxv1.UpdateMessageResponse], error) {
	return c.updateMessage.CallUnary(ctx, req)
}

// DeleteMessage calls outbox.v1.MessageService.DeleteMessage.
func (c *messageServiceClient) DeleteMessage(ctx context.Context, req *connect.Request[outboxv1.DeleteMessageRequest]) (*connect.Response[outboxv1.DeleteMessageResponse], error) {
	return c.deleteMessage.CallUnary(ctx, req)
}

// ListMessages calls outbox.v1.MessageService.ListMessages.
func (c *messageServiceClient) ListMessages(ctx context.Context, req *connect.Request[outboxv1.ListMessagesRequest]) (*connect.Response[outboxv1.ListMessagesResponse], error) {
	return c.listMessages.CallUnary(ctx, req)
}

// SendReadReceipt calls outbox.v1.MessageService.SendReadReceipt.
func (c *messageServiceClient) SendReadReceipt(ctx context.Context, req *connect.Request[outboxv1.SendReadReceiptRequest]) (*connect.Response[outboxv1.SendReadReceiptResponse], error) {
	return c.sendReadReceipt.CallUnary(ctx, req)
}

// SendTypingIndicator calls outbox.v1.MessageService.SendTypingIndicator.
func (c *messageServiceClient) SendTypingIndicator(ctx context.Context, req *connect.Request[outboxv1.SendTypingIndicatorRequest]) (*connect.Response[outboxv1.SendTypingIndicatorResponse], error) {
	return c.sendTypingIndicator.CallUnary(ctx, req)
}

// MessageServiceHandler is an implementation of the outbox.v1.MessageService service.
type MessageServiceHandler interface {
	// Creates and sends a message. Also used for reactions (set reply_to
	// and parts[0].disposition = REACTION) and edits (set replaced).
	CreateMessage(context.Context, *connect.Request[outboxv1.CreateMessageRequest]) (*connect.Response[outboxv1.CreateMessageResponse], error)
	// Updates (edits) a previously sent message's content.
	UpdateMessage(context.Context, *connect.Request[outboxv1.UpdateMessageRequest]) (*connect.Response[outboxv1.UpdateMessageResponse], error)
	// Deletes a message. Returns the updated message with delete_time set.
	DeleteMessage(context.Context, *connect.Request[outboxv1.DeleteMessageRequest]) (*connect.Response[outboxv1.DeleteMessageResponse], error)
	ListMessages(context.Context, *connect.Request[outboxv1.ListMessagesRequest]) (*connect.Response[outboxv1.ListMessagesResponse], error)
	SendReadReceipt(context.Context, *connect.Request[outboxv1.SendReadReceiptRequest]) (*connect.Response[outboxv1.SendReadReceiptResponse], error)
	SendTypingIndicator(context.Context, *connect.Request[outboxv1.SendTypingIndicatorRequest]) (*connect.Response[outboxv1.SendTypingIndicatorResponse], error)
}

// NewMessageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMessageServiceHandler(svc MessageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	messageServiceMethods := outboxv1.File_outbox_v1_message_proto.Services().ByName("MessageService").Methods()
	messageServiceCreateMessageHandler := connect.NewUnaryHandler(
		MessageServiceCreateMessageProcedure,
		svc.CreateMessage,
		connect.WithSchema(messageServiceMethods.ByName("CreateMessage")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceUpdateMessageHandler := connect.NewUnaryHandler(
		MessageServiceUpdateMessageProcedure,
		svc.UpdateMessage,
		connect.WithSchema(messageServiceMethods.ByName("UpdateMessage")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceDeleteMessageHandler := connect.NewUnaryHandler(
		MessageServiceDeleteMessageProcedure,
		svc.DeleteMessage,
		connect.WithSchema(messageServiceMethods.ByName("DeleteMessage")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceListMessagesHandler := connect.NewUnaryHandler(
		MessageServiceListMessagesProcedure,
		svc.ListMessages,
		connect.WithSchema(messageServiceMethods.ByName("ListMessages")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceSendReadReceiptHandler := connect.NewUnaryHandler(
		MessageServiceSendReadReceiptProcedure,
		svc.SendReadReceipt,
		connect.WithSchema(messageServiceMethods.ByName("SendReadReceipt")),
		connect.WithHandlerOptions(opts...),
	)
	messageServiceSendTypingIndicatorHandler := connect.NewUnaryHandler(
		MessageServiceSendTypingIndicatorProcedure,
		svc.SendTypingIndicator,
		connect.WithSchema(messageServiceMethods.ByName("SendTypingIndicator")),
		connect.WithHandlerOptions(opts...),
	)
	return "/outbox.v1.MessageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MessageServiceCreateMessageProcedure:
			messageServiceCreateMessageHandler.ServeHTTP(w, r)
		case MessageServiceUpdateMessageProcedure:
			messageServiceUpdateMessageHandler.ServeHTTP(w, r)
		case MessageServiceDeleteMessageProcedure:
			messageServiceDeleteMessageHandler.ServeHTTP(w, r)
		case MessageServiceListMessagesProcedure:
			messageServiceListMessagesHandler.ServeHTTP(w, r)
		case MessageServiceSendReadReceiptProcedure:
			messageServiceSendReadReceiptHandler.ServeHTTP(w, r)
		case MessageServiceSendTypingIndicatorProcedure:
			messageServiceSendTypingIndicatorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMessageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMessageServiceHandler struct{}

func (UnimplementedMessageServiceHandler) CreateMessage(context.Context, *connect.Request[outboxv1.CreateMessageRequest]) (*connect.Response[outboxv1.CreateMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.MessageService.CreateMessage is not implemented"))
}

func (UnimplementedMessageServiceHandler) UpdateMessage(context.Context, *connect.Request[outboxv1.UpdateMessageRequest]) (*connect.Response[outboxv1.UpdateMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.MessageService.UpdateMessage is not implemented"))
}

func (UnimplementedMessageServiceHandler) DeleteMessage(context.Context, *connect.Request[outboxv1.DeleteMessageRequest]) (*connect.Response[outboxv1.DeleteMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.MessageService.DeleteMessage is not implemented"))
}

func (UnimplementedMessageServiceHandler) ListMessages(context.Context, *connect.Request[outboxv1.ListMessagesRequest]) (*connect.Response[outboxv1.ListMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.MessageService.ListMessages is not implemented"))
}

func (UnimplementedMessageServiceHandler) SendReadReceipt(context.Context, *connect.Request[outboxv1.SendReadReceiptRequest]) (*connect.Response[outboxv1.SendReadReceiptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.MessageService.SendReadReceipt is not implemented"))
}

func (UnimplementedMessageServiceHandler) SendTypingIndicator(context.Context, *connect.Request[outboxv1.SendTypingIndicatorRequest]) (*connect.Response[outboxv1.SendTypingIndicatorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("outbox.v1.MessageService.SendTypingIndicator is not implemented"))
}
