// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: outbox/v1/channel.proto

package outboxv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel represents a communication delivery channel (e.g., WhatsApp, Slack, email)
// supported by the Outbox platform. Channels are system-managed read-only resources;
// they cannot be created or deleted via the API.
// Channels are immutable after creation — no update_time is provided.
type Channel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Format: channels/{channel_type}
	Name          string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Capabilities  *Channel_Capabilities  `protobuf:"bytes,2,opt,name=capabilities" json:"capabilities,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_outbox_v1_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_outbox_v1_channel_proto_rawDescGZIP(), []int{0}
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetCapabilities() *Channel_Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Channel) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type ListChannelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of channels to return (0 = server default, max 1000).
	PageSize      int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_outbox_v1_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ListChannelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChannelsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels" json:"channels,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	TotalSize     int32                  `protobuf:"varint,3,opt,name=total_size,json=totalSize" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_outbox_v1_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_channel_proto_rawDescGZIP(), []int{2}
}

func (x *ListChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ListChannelsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListChannelsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type GetChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Format: channels/{channel_type}
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_outbox_v1_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_channel_proto_rawDescGZIP(), []int{3}
}

func (x *GetChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelResponse) Reset() {
	*x = GetChannelResponse{}
	mi := &file_outbox_v1_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelResponse) ProtoMessage() {}

func (x *GetChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelResponse.ProtoReflect.Descriptor instead.
func (*GetChannelResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_channel_proto_rawDescGZIP(), []int{4}
}

func (x *GetChannelResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type Channel_Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the channel supports group conversations (message.group_id).
	Groups bool `protobuf:"varint,1,opt,name=groups" json:"groups,omitempty"`
	// True if the channel supports emoji/sticker reactions (MessagePart with
	// DISPOSITION_REACTION). Covers all reaction types, not just text/plain.
	Reactions bool `protobuf:"varint,2,opt,name=reactions" json:"reactions,omitempty"`
	// True if the channel supports message edits (Message.replaced set
	// with non-empty parts). Applies to both inbound and outbound messages.
	Edits bool `protobuf:"varint,3,opt,name=edits" json:"edits,omitempty"`
	// True if the channel supports message deletion (Message.replaced set
	// with empty parts). DELETION_SCOPE_FOR_EVERYONE requires additional channel
	// support; check channel documentation for scope-level details.
	Deletions bool `protobuf:"varint,4,opt,name=deletions" json:"deletions,omitempty"`
	// True if the channel delivers read receipts (ReadReceiptEvent).
	ReadReceipts bool `protobuf:"varint,5,opt,name=read_receipts,json=readReceipts" json:"read_receipts,omitempty"`
	// True if the channel delivers typing indicators (TypingIndicatorEvent).
	TypingIndicators bool `protobuf:"varint,6,opt,name=typing_indicators,json=typingIndicators" json:"typing_indicators,omitempty"`
	// Exhaustive list of MIME types accepted as MessagePart.content_type.
	// Covers content type only — not all dispositions are valid for every type.
	// See channel documentation for disposition-level constraints.
	SupportedContentTypes []string `protobuf:"bytes,7,rep,name=supported_content_types,json=supportedContentTypes" json:"supported_content_types,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Channel_Capabilities) Reset() {
	*x = Channel_Capabilities{}
	mi := &file_outbox_v1_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel_Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel_Capabilities) ProtoMessage() {}

func (x *Channel_Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel_Capabilities.ProtoReflect.Descriptor instead.
func (*Channel_Capabilities) Descriptor() ([]byte, []int) {
	return file_outbox_v1_channel_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Channel_Capabilities) GetGroups() bool {
	if x != nil {
		return x.Groups
	}
	return false
}

func (x *Channel_Capabilities) GetReactions() bool {
	if x != nil {
		return x.Reactions
	}
	return false
}

func (x *Channel_Capabilities) GetEdits() bool {
	if x != nil {
		return x.Edits
	}
	return false
}

func (x *Channel_Capabilities) GetDeletions() bool {
	if x != nil {
		return x.Deletions
	}
	return false
}

func (x *Channel_Capabilities) GetReadReceipts() bool {
	if x != nil {
		return x.ReadReceipts
	}
	return false
}

func (x *Channel_Capabilities) GetTypingIndicators() bool {
	if x != nil {
		return x.TypingIndicators
	}
	return false
}

func (x *Channel_Capabilities) GetSupportedContentTypes() []string {
	if x != nil {
		return x.SupportedContentTypes
	}
	return nil
}

var File_outbox_v1_channel_proto protoreflect.FileDescriptor

const file_outbox_v1_channel_proto_rawDesc = "" +
	"\n" +
	"\x17outbox/v1/channel.proto\x12\toutbox.v1\x1a\x1bbuf/validate/validate.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x04\n" +
	"\aChannel\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12H\n" +
	"\fcapabilities\x18\x02 \x01(\v2\x1f.outbox.v1.Channel.CapabilitiesB\x03\xe0A\x03R\fcapabilities\x12@\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x1a\xa5\x02\n" +
	"\fCapabilities\x12\x1b\n" +
	"\x06groups\x18\x01 \x01(\bB\x03\xe0A\x03R\x06groups\x12!\n" +
	"\treactions\x18\x02 \x01(\bB\x03\xe0A\x03R\treactions\x12\x19\n" +
	"\x05edits\x18\x03 \x01(\bB\x03\xe0A\x03R\x05edits\x12!\n" +
	"\tdeletions\x18\x04 \x01(\bB\x03\xe0A\x03R\tdeletions\x12(\n" +
	"\rread_receipts\x18\x05 \x01(\bB\x03\xe0A\x03R\freadReceipts\x120\n" +
	"\x11typing_indicators\x18\x06 \x01(\bB\x03\xe0A\x03R\x10typingIndicators\x12;\n" +
	"\x17supported_content_types\x18\a \x03(\tB\x03\xe0A\x03R\x15supportedContentTypes:D\xeaAA\n" +
	"\x13outbox.chat/Channel\x12\x17channels/{channel_type}*\bchannels2\achannel\"e\n" +
	"\x13ListChannelsRequest\x12*\n" +
	"\tpage_size\x18\x01 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\x03\xe0A\x01R\tpageToken\"\x8d\x01\n" +
	"\x14ListChannelsResponse\x12.\n" +
	"\bchannels\x18\x01 \x03(\v2\x12.outbox.v1.ChannelR\bchannels\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"K\n" +
	"\x11GetChannelRequest\x126\n" +
	"\x04name\x18\x01 \x01(\tB\"\xe0A\x02\xfaA\x15\n" +
	"\x13outbox.chat/Channel\xbaH\x04r\x02\x10\x01R\x04name\"G\n" +
	"\x12GetChannelResponse\x121\n" +
	"\achannel\x18\x01 \x01(\v2\x12.outbox.v1.ChannelB\x03\xe0A\x03R\achannel2\xba\x01\n" +
	"\x0eChannelService\x12R\n" +
	"\n" +
	"GetChannel\x12\x1c.outbox.v1.GetChannelRequest\x1a\x1d.outbox.v1.GetChannelResponse\"\a\xdaA\x04name\x12T\n" +
	"\fListChannels\x12\x1e.outbox.v1.ListChannelsRequest\x1a\x1f.outbox.v1.ListChannelsResponse\"\x03\xdaA\x00BPZIgithub.com/getoutbox/outbox-internal/go/outbox-api/gen/outbox/v1;outboxv1\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_outbox_v1_channel_proto_rawDescOnce sync.Once
	file_outbox_v1_channel_proto_rawDescData []byte
)

func file_outbox_v1_channel_proto_rawDescGZIP() []byte {
	file_outbox_v1_channel_proto_rawDescOnce.Do(func() {
		file_outbox_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outbox_v1_channel_proto_rawDesc), len(file_outbox_v1_channel_proto_rawDesc)))
	})
	return file_outbox_v1_channel_proto_rawDescData
}

var file_outbox_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_outbox_v1_channel_proto_goTypes = []any{
	(*Channel)(nil),               // 0: outbox.v1.Channel
	(*ListChannelsRequest)(nil),   // 1: outbox.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),  // 2: outbox.v1.ListChannelsResponse
	(*GetChannelRequest)(nil),     // 3: outbox.v1.GetChannelRequest
	(*GetChannelResponse)(nil),    // 4: outbox.v1.GetChannelResponse
	(*Channel_Capabilities)(nil),  // 5: outbox.v1.Channel.Capabilities
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_outbox_v1_channel_proto_depIdxs = []int32{
	5, // 0: outbox.v1.Channel.capabilities:type_name -> outbox.v1.Channel.Capabilities
	6, // 1: outbox.v1.Channel.create_time:type_name -> google.protobuf.Timestamp
	0, // 2: outbox.v1.ListChannelsResponse.channels:type_name -> outbox.v1.Channel
	0, // 3: outbox.v1.GetChannelResponse.channel:type_name -> outbox.v1.Channel
	3, // 4: outbox.v1.ChannelService.GetChannel:input_type -> outbox.v1.GetChannelRequest
	1, // 5: outbox.v1.ChannelService.ListChannels:input_type -> outbox.v1.ListChannelsRequest
	4, // 6: outbox.v1.ChannelService.GetChannel:output_type -> outbox.v1.GetChannelResponse
	2, // 7: outbox.v1.ChannelService.ListChannels:output_type -> outbox.v1.ListChannelsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_outbox_v1_channel_proto_init() }
func file_outbox_v1_channel_proto_init() {
	if File_outbox_v1_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outbox_v1_channel_proto_rawDesc), len(file_outbox_v1_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outbox_v1_channel_proto_goTypes,
		DependencyIndexes: file_outbox_v1_channel_proto_depIdxs,
		MessageInfos:      file_outbox_v1_channel_proto_msgTypes,
	}.Build()
	File_outbox_v1_channel_proto = out.File
	file_outbox_v1_channel_proto_goTypes = nil
	file_outbox_v1_channel_proto_depIdxs = nil
}
