// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: outbox/v1/connector_config.proto

package outboxv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityPubConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUrl      string                 `protobuf:"bytes,1,opt,name=actor_url,json=actorUrl" json:"actor_url,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityPubConfig) Reset() {
	*x = ActivityPubConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityPubConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityPubConfig) ProtoMessage() {}

func (x *ActivityPubConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityPubConfig.ProtoReflect.Descriptor instead.
func (*ActivityPubConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityPubConfig) GetActorUrl() string {
	if x != nil {
		return x.ActorUrl
	}
	return ""
}

func (x *ActivityPubConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type ApnsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId" json:"key_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApnsConfig) Reset() {
	*x = ApnsConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApnsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApnsConfig) ProtoMessage() {}

func (x *ApnsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApnsConfig.ProtoReflect.Descriptor instead.
func (*ApnsConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{1}
}

func (x *ApnsConfig) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ApnsConfig) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ApnsConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type AppleMessagesConfig struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BusinessId string                 `protobuf:"bytes,1,opt,name=business_id,json=businessId" json:"business_id,omitempty"`
	// MSP delegate ID. Omit if acting as your own MSP.
	MspId         string `protobuf:"bytes,2,opt,name=msp_id,json=mspId" json:"msp_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppleMessagesConfig) Reset() {
	*x = AppleMessagesConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppleMessagesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppleMessagesConfig) ProtoMessage() {}

func (x *AppleMessagesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppleMessagesConfig.ProtoReflect.Descriptor instead.
func (*AppleMessagesConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{2}
}

func (x *AppleMessagesConfig) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *AppleMessagesConfig) GetMspId() string {
	if x != nil {
		return x.MspId
	}
	return ""
}

type BlueskyConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AT Protocol sessions expire ~2h. Backend manages session refresh
	// using handle+app_password (stored). Developer treats this as static.
	Handle        string `protobuf:"bytes,1,opt,name=handle" json:"handle,omitempty"`
	AppPassword   string `protobuf:"bytes,2,opt,name=app_password,json=appPassword" json:"app_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlueskyConfig) Reset() {
	*x = BlueskyConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlueskyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueskyConfig) ProtoMessage() {}

func (x *BlueskyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueskyConfig.ProtoReflect.Descriptor instead.
func (*BlueskyConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{3}
}

func (x *BlueskyConfig) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *BlueskyConfig) GetAppPassword() string {
	if x != nil {
		return x.AppPassword
	}
	return ""
}

type DiscordConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotToken      string                 `protobuf:"bytes,1,opt,name=bot_token,json=botToken" json:"bot_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordConfig) Reset() {
	*x = DiscordConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordConfig) ProtoMessage() {}

func (x *DiscordConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordConfig.ProtoReflect.Descriptor instead.
func (*DiscordConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{4}
}

func (x *DiscordConfig) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

type EmailConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey" json:"api_key,omitempty"`
	FromAddress   string                 `protobuf:"bytes,2,opt,name=from_address,json=fromAddress" json:"from_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailConfig) Reset() {
	*x = EmailConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailConfig) ProtoMessage() {}

func (x *EmailConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailConfig.ProtoReflect.Descriptor instead.
func (*EmailConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{5}
}

func (x *EmailConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *EmailConfig) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

type FcmConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountKey string                 `protobuf:"bytes,1,opt,name=service_account_key,json=serviceAccountKey" json:"service_account_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FcmConfig) Reset() {
	*x = FcmConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FcmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FcmConfig) ProtoMessage() {}

func (x *FcmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FcmConfig.ProtoReflect.Descriptor instead.
func (*FcmConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{6}
}

func (x *FcmConfig) GetServiceAccountKey() string {
	if x != nil {
		return x.ServiceAccountKey
	}
	return ""
}

type FreshchatConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	ApiToken      string                 `protobuf:"bytes,2,opt,name=api_token,json=apiToken" json:"api_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreshchatConfig) Reset() {
	*x = FreshchatConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreshchatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreshchatConfig) ProtoMessage() {}

func (x *FreshchatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreshchatConfig.ProtoReflect.Descriptor instead.
func (*FreshchatConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{7}
}

func (x *FreshchatConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *FreshchatConfig) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

// InAppConfig has no required credentials; in-app delivery is handled by the SDK.
type InAppConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InAppConfig) Reset() {
	*x = InAppConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InAppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InAppConfig) ProtoMessage() {}

func (x *InAppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InAppConfig.ProtoReflect.Descriptor instead.
func (*InAppConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{8}
}

type MatrixConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeserverUrl string                 `protobuf:"bytes,1,opt,name=homeserver_url,json=homeserverUrl" json:"homeserver_url,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixConfig) Reset() {
	*x = MatrixConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixConfig) ProtoMessage() {}

func (x *MatrixConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixConfig.ProtoReflect.Descriptor instead.
func (*MatrixConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{9}
}

func (x *MatrixConfig) GetHomeserverUrl() string {
	if x != nil {
		return x.HomeserverUrl
	}
	return ""
}

func (x *MatrixConfig) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type MqttConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerUrl     string                 `protobuf:"bytes,1,opt,name=broker_url,json=brokerUrl" json:"broker_url,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MqttConfig) Reset() {
	*x = MqttConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MqttConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqttConfig) ProtoMessage() {}

func (x *MqttConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqttConfig.ProtoReflect.Descriptor instead.
func (*MqttConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{10}
}

func (x *MqttConfig) GetBrokerUrl() string {
	if x != nil {
		return x.BrokerUrl
	}
	return ""
}

func (x *MqttConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MqttConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RcsConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountKey string                 `protobuf:"bytes,1,opt,name=service_account_key,json=serviceAccountKey" json:"service_account_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RcsConfig) Reset() {
	*x = RcsConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RcsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RcsConfig) ProtoMessage() {}

func (x *RcsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RcsConfig.ProtoReflect.Descriptor instead.
func (*RcsConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{11}
}

func (x *RcsConfig) GetServiceAccountKey() string {
	if x != nil {
		return x.ServiceAccountKey
	}
	return ""
}

type SignalConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effectively a secret — unauthenticated signal-cli REST API endpoint.
	Url           string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	PhoneNumber   string `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalConfig) Reset() {
	*x = SignalConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalConfig) ProtoMessage() {}

func (x *SignalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalConfig.ProtoReflect.Descriptor instead.
func (*SignalConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{12}
}

func (x *SignalConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SignalConfig) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type SmsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountSid    string                 `protobuf:"bytes,1,opt,name=account_sid,json=accountSid" json:"account_sid,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
	FromNumber    string                 `protobuf:"bytes,3,opt,name=from_number,json=fromNumber" json:"from_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsConfig) Reset() {
	*x = SmsConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsConfig) ProtoMessage() {}

func (x *SmsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsConfig.ProtoReflect.Descriptor instead.
func (*SmsConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{13}
}

func (x *SmsConfig) GetAccountSid() string {
	if x != nil {
		return x.AccountSid
	}
	return ""
}

func (x *SmsConfig) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *SmsConfig) GetFromNumber() string {
	if x != nil {
		return x.FromNumber
	}
	return ""
}

type TelegramConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotToken      string                 `protobuf:"bytes,1,opt,name=bot_token,json=botToken" json:"bot_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramConfig) Reset() {
	*x = TelegramConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramConfig) ProtoMessage() {}

func (x *TelegramConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramConfig.ProtoReflect.Descriptor instead.
func (*TelegramConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{14}
}

func (x *TelegramConfig) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

type ViberConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViberConfig) Reset() {
	*x = ViberConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViberConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViberConfig) ProtoMessage() {}

func (x *ViberConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViberConfig.ProtoReflect.Descriptor instead.
func (*ViberConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{15}
}

func (x *ViberConfig) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type WebPushConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VapidPublicKey  string                 `protobuf:"bytes,1,opt,name=vapid_public_key,json=vapidPublicKey" json:"vapid_public_key,omitempty"`
	VapidPrivateKey string                 `protobuf:"bytes,2,opt,name=vapid_private_key,json=vapidPrivateKey" json:"vapid_private_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebPushConfig) Reset() {
	*x = WebPushConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPushConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPushConfig) ProtoMessage() {}

func (x *WebPushConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPushConfig.ProtoReflect.Descriptor instead.
func (*WebPushConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{16}
}

func (x *WebPushConfig) GetVapidPublicKey() string {
	if x != nil {
		return x.VapidPublicKey
	}
	return ""
}

func (x *WebPushConfig) GetVapidPrivateKey() string {
	if x != nil {
		return x.VapidPrivateKey
	}
	return ""
}

type XmppConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XmppConfig) Reset() {
	*x = XmppConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XmppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XmppConfig) ProtoMessage() {}

func (x *XmppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XmppConfig.ProtoReflect.Descriptor instead.
func (*XmppConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{17}
}

func (x *XmppConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *XmppConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *XmppConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Static, app credentials (headless token exchange, no user redirect).
type TeamsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId" json:"tenant_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamsConfig) Reset() {
	*x = TeamsConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamsConfig) ProtoMessage() {}

func (x *TeamsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamsConfig.ProtoReflect.Descriptor instead.
func (*TeamsConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{18}
}

func (x *TeamsConfig) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TeamsConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TeamsConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type WechatConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatConfig) Reset() {
	*x = WechatConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatConfig) ProtoMessage() {}

func (x *WechatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatConfig.ProtoReflect.Descriptor instead.
func (*WechatConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{19}
}

func (x *WechatConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WechatConfig) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *WechatConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HubspotConfig struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ClientId     string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	// Populated after OAuth completion.
	PortalId      string `protobuf:"bytes,3,opt,name=portal_id,json=portalId" json:"portal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubspotConfig) Reset() {
	*x = HubspotConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubspotConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubspotConfig) ProtoMessage() {}

func (x *HubspotConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubspotConfig.ProtoReflect.Descriptor instead.
func (*HubspotConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{20}
}

func (x *HubspotConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HubspotConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *HubspotConfig) GetPortalId() string {
	if x != nil {
		return x.PortalId
	}
	return ""
}

type IntercomConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Note: Intercom tokens are permanent (no expiry, no refresh, no revocation).
	AppId         string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppSecret     string `protobuf:"bytes,2,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	WorkspaceName string `protobuf:"bytes,3,opt,name=workspace_name,json=workspaceName" json:"workspace_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntercomConfig) Reset() {
	*x = IntercomConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntercomConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntercomConfig) ProtoMessage() {}

func (x *IntercomConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntercomConfig.ProtoReflect.Descriptor instead.
func (*IntercomConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{21}
}

func (x *IntercomConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *IntercomConfig) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *IntercomConfig) GetWorkspaceName() string {
	if x != nil {
		return x.WorkspaceName
	}
	return ""
}

type LinkedinConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Note: LinkedIn tokens expire ~60 days with NO refresh token.
	// Backend auto-transitions to ERROR on expiry. Developer must
	// call ReauthorizeConnector to re-auth.
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret  string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	ProfileName   string `protobuf:"bytes,3,opt,name=profile_name,json=profileName" json:"profile_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedinConfig) Reset() {
	*x = LinkedinConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedinConfig) ProtoMessage() {}

func (x *LinkedinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedinConfig.ProtoReflect.Descriptor instead.
func (*LinkedinConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{22}
}

func (x *LinkedinConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LinkedinConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *LinkedinConfig) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

type LiveChatConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveChatConfig) Reset() {
	*x = LiveChatConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveChatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveChatConfig) ProtoMessage() {}

func (x *LiveChatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveChatConfig.ProtoReflect.Descriptor instead.
func (*LiveChatConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{23}
}

func (x *LiveChatConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LiveChatConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type RedditConfig struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ClientId     string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	// Populated after OAuth completion.
	Username      string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedditConfig) Reset() {
	*x = RedditConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedditConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedditConfig) ProtoMessage() {}

func (x *RedditConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedditConfig.ProtoReflect.Descriptor instead.
func (*RedditConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{24}
}

func (x *RedditConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RedditConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *RedditConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ThreadsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadsConfig) Reset() {
	*x = ThreadsConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadsConfig) ProtoMessage() {}

func (x *ThreadsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadsConfig.ProtoReflect.Descriptor instead.
func (*ThreadsConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{25}
}

func (x *ThreadsConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ThreadsConfig) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *ThreadsConfig) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TiktokConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TikTok's name for client_id.
	ClientKey     string `protobuf:"bytes,1,opt,name=client_key,json=clientKey" json:"client_key,omitempty"`
	ClientSecret  string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	OpenId        string `protobuf:"bytes,3,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TiktokConfig) Reset() {
	*x = TiktokConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TiktokConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiktokConfig) ProtoMessage() {}

func (x *TiktokConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiktokConfig.ProtoReflect.Descriptor instead.
func (*TiktokConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{26}
}

func (x *TiktokConfig) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *TiktokConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *TiktokConfig) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type TwitchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	BotUsername   string                 `protobuf:"bytes,3,opt,name=bot_username,json=botUsername" json:"bot_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwitchConfig) Reset() {
	*x = TwitchConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwitchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitchConfig) ProtoMessage() {}

func (x *TwitchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitchConfig.ProtoReflect.Descriptor instead.
func (*TwitchConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{27}
}

func (x *TwitchConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TwitchConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *TwitchConfig) GetBotUsername() string {
	if x != nil {
		return x.BotUsername
	}
	return ""
}

type ZaloConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	OaId          string                 `protobuf:"bytes,3,opt,name=oa_id,json=oaId" json:"oa_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZaloConfig) Reset() {
	*x = ZaloConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZaloConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZaloConfig) ProtoMessage() {}

func (x *ZaloConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZaloConfig.ProtoReflect.Descriptor instead.
func (*ZaloConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{28}
}

func (x *ZaloConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ZaloConfig) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *ZaloConfig) GetOaId() string {
	if x != nil {
		return x.OaId
	}
	return ""
}

type ZendeskConfig struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Subdomain    string                 `protobuf:"bytes,1,opt,name=subdomain" json:"subdomain,omitempty"`
	ClientId     string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	// Note: Zendesk tokens are permanent (no expiry, no refresh).
	AccountName   string `protobuf:"bytes,4,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZendeskConfig) Reset() {
	*x = ZendeskConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZendeskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZendeskConfig) ProtoMessage() {}

func (x *ZendeskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZendeskConfig.ProtoReflect.Descriptor instead.
func (*ZendeskConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{29}
}

func (x *ZendeskConfig) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *ZendeskConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ZendeskConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *ZendeskConfig) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type InstagramConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppId              string                 `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppSecret          string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	PageId             string                 `protobuf:"bytes,3,opt,name=page_id,json=pageId" json:"page_id,omitempty"`
	InstagramAccountId string                 `protobuf:"bytes,4,opt,name=instagram_account_id,json=instagramAccountId" json:"instagram_account_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InstagramConfig) Reset() {
	*x = InstagramConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstagramConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstagramConfig) ProtoMessage() {}

func (x *InstagramConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstagramConfig.ProtoReflect.Descriptor instead.
func (*InstagramConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{30}
}

func (x *InstagramConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *InstagramConfig) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *InstagramConfig) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *InstagramConfig) GetInstagramAccountId() string {
	if x != nil {
		return x.InstagramAccountId
	}
	return ""
}

type MessengerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	PageId        string                 `protobuf:"bytes,3,opt,name=page_id,json=pageId" json:"page_id,omitempty"`
	PageName      string                 `protobuf:"bytes,4,opt,name=page_name,json=pageName" json:"page_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessengerConfig) Reset() {
	*x = MessengerConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessengerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessengerConfig) ProtoMessage() {}

func (x *MessengerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessengerConfig.ProtoReflect.Descriptor instead.
func (*MessengerConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{31}
}

func (x *MessengerConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MessengerConfig) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *MessengerConfig) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *MessengerConfig) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

type WhatsAppConfig struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AppId     string                 `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppSecret string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	// Populated after Embedded Signup.
	WabaId             string `protobuf:"bytes,3,opt,name=waba_id,json=wabaId" json:"waba_id,omitempty"`
	PhoneNumberId      string `protobuf:"bytes,4,opt,name=phone_number_id,json=phoneNumberId" json:"phone_number_id,omitempty"`
	DisplayPhoneNumber string `protobuf:"bytes,5,opt,name=display_phone_number,json=displayPhoneNumber" json:"display_phone_number,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WhatsAppConfig) Reset() {
	*x = WhatsAppConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhatsAppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhatsAppConfig) ProtoMessage() {}

func (x *WhatsAppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhatsAppConfig.ProtoReflect.Descriptor instead.
func (*WhatsAppConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{32}
}

func (x *WhatsAppConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WhatsAppConfig) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *WhatsAppConfig) GetWabaId() string {
	if x != nil {
		return x.WabaId
	}
	return ""
}

func (x *WhatsAppConfig) GetPhoneNumberId() string {
	if x != nil {
		return x.PhoneNumberId
	}
	return ""
}

func (x *WhatsAppConfig) GetDisplayPhoneNumber() string {
	if x != nil {
		return x.DisplayPhoneNumber
	}
	return ""
}

type GoogleChatConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bot mode (direct)
	ServiceAccountKey string `protobuf:"bytes,1,opt,name=service_account_key,json=serviceAccountKey" json:"service_account_key,omitempty"`
	// OAuth mode
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret  string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	SpaceId       string `protobuf:"bytes,4,opt,name=space_id,json=spaceId" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleChatConfig) Reset() {
	*x = GoogleChatConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleChatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleChatConfig) ProtoMessage() {}

func (x *GoogleChatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleChatConfig.ProtoReflect.Descriptor instead.
func (*GoogleChatConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{33}
}

func (x *GoogleChatConfig) GetServiceAccountKey() string {
	if x != nil {
		return x.ServiceAccountKey
	}
	return ""
}

func (x *GoogleChatConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GoogleChatConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *GoogleChatConfig) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type KakaoTalkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BizMessage mode (direct)
	BizClientId     string `protobuf:"bytes,1,opt,name=biz_client_id,json=bizClientId" json:"biz_client_id,omitempty"`
	BizClientSecret string `protobuf:"bytes,2,opt,name=biz_client_secret,json=bizClientSecret" json:"biz_client_secret,omitempty"`
	// Personal OAuth mode
	RestApiKey   string `protobuf:"bytes,3,opt,name=rest_api_key,json=restApiKey" json:"rest_api_key,omitempty"`
	ClientSecret string `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	// OUTPUT_ONLY
	KakaoUserId   string `protobuf:"bytes,5,opt,name=kakao_user_id,json=kakaoUserId" json:"kakao_user_id,omitempty"`
	ChannelName   string `protobuf:"bytes,6,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KakaoTalkConfig) Reset() {
	*x = KakaoTalkConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KakaoTalkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KakaoTalkConfig) ProtoMessage() {}

func (x *KakaoTalkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KakaoTalkConfig.ProtoReflect.Descriptor instead.
func (*KakaoTalkConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{34}
}

func (x *KakaoTalkConfig) GetBizClientId() string {
	if x != nil {
		return x.BizClientId
	}
	return ""
}

func (x *KakaoTalkConfig) GetBizClientSecret() string {
	if x != nil {
		return x.BizClientSecret
	}
	return ""
}

func (x *KakaoTalkConfig) GetRestApiKey() string {
	if x != nil {
		return x.RestApiKey
	}
	return ""
}

func (x *KakaoTalkConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *KakaoTalkConfig) GetKakaoUserId() string {
	if x != nil {
		return x.KakaoUserId
	}
	return ""
}

func (x *KakaoTalkConfig) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type LarkConfig struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AppId     string                 `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppSecret string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	// false (default) = bot mode (tenant_access_token, direct → ACTIVE immediately)
	// true  = user OAuth mode (AUTHORIZING + redirect)
	UserOauth     bool   `protobuf:"varint,3,opt,name=user_oauth,json=userOauth" json:"user_oauth,omitempty"`
	TenantName    string `protobuf:"bytes,4,opt,name=tenant_name,json=tenantName" json:"tenant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LarkConfig) Reset() {
	*x = LarkConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LarkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LarkConfig) ProtoMessage() {}

func (x *LarkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LarkConfig.ProtoReflect.Descriptor instead.
func (*LarkConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{35}
}

func (x *LarkConfig) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *LarkConfig) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *LarkConfig) GetUserOauth() bool {
	if x != nil {
		return x.UserOauth
	}
	return false
}

func (x *LarkConfig) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

type LineConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Direct mode
	ChannelToken string `protobuf:"bytes,1,opt,name=channel_token,json=channelToken" json:"channel_token,omitempty"`
	// Required in both modes for webhook verification.
	ChannelSecret string `protobuf:"bytes,2,opt,name=channel_secret,json=channelSecret" json:"channel_secret,omitempty"`
	// OAuth mode
	ChannelId     string `protobuf:"bytes,3,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	BotName       string `protobuf:"bytes,4,opt,name=bot_name,json=botName" json:"bot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineConfig) Reset() {
	*x = LineConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineConfig) ProtoMessage() {}

func (x *LineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineConfig.ProtoReflect.Descriptor instead.
func (*LineConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{36}
}

func (x *LineConfig) GetChannelToken() string {
	if x != nil {
		return x.ChannelToken
	}
	return ""
}

func (x *LineConfig) GetChannelSecret() string {
	if x != nil {
		return x.ChannelSecret
	}
	return ""
}

func (x *LineConfig) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *LineConfig) GetBotName() string {
	if x != nil {
		return x.BotName
	}
	return ""
}

type MattermostConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Url   string                 `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	// Direct mode
	BotToken string `protobuf:"bytes,2,opt,name=bot_token,json=botToken" json:"bot_token,omitempty"`
	// Programmatic mode: consumed during CreateConnector, NEVER persisted.
	// Backend creates bot via POST /api/v4/bots, stores resulting bot_token.
	AdminToken    string `protobuf:"bytes,3,opt,name=admin_token,json=adminToken" json:"admin_token,omitempty"`
	BotUsername   string `protobuf:"bytes,4,opt,name=bot_username,json=botUsername" json:"bot_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MattermostConfig) Reset() {
	*x = MattermostConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MattermostConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MattermostConfig) ProtoMessage() {}

func (x *MattermostConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MattermostConfig.ProtoReflect.Descriptor instead.
func (*MattermostConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{37}
}

func (x *MattermostConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MattermostConfig) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *MattermostConfig) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *MattermostConfig) GetBotUsername() string {
	if x != nil {
		return x.BotUsername
	}
	return ""
}

type SlackConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Direct mode
	BotToken string `protobuf:"bytes,1,opt,name=bot_token,json=botToken" json:"bot_token,omitempty"`
	// HMAC-SHA256 signing secret for verifying incoming webhook events.
	SigningSecret string `protobuf:"bytes,2,opt,name=signing_secret,json=signingSecret" json:"signing_secret,omitempty"`
	// OAuth mode
	ClientId     string `protobuf:"bytes,3,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	// OUTPUT_ONLY
	TeamName      string `protobuf:"bytes,5,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
	BotUserId     string `protobuf:"bytes,6,opt,name=bot_user_id,json=botUserId" json:"bot_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlackConfig) Reset() {
	*x = SlackConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlackConfig) ProtoMessage() {}

func (x *SlackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlackConfig.ProtoReflect.Descriptor instead.
func (*SlackConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{38}
}

func (x *SlackConfig) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *SlackConfig) GetSigningSecret() string {
	if x != nil {
		return x.SigningSecret
	}
	return ""
}

func (x *SlackConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SlackConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *SlackConfig) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *SlackConfig) GetBotUserId() string {
	if x != nil {
		return x.BotUserId
	}
	return ""
}

type WebexConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Direct mode
	BotToken string `protobuf:"bytes,1,opt,name=bot_token,json=botToken" json:"bot_token,omitempty"`
	// OAuth mode
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret  string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	DisplayName   string `protobuf:"bytes,4,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebexConfig) Reset() {
	*x = WebexConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebexConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebexConfig) ProtoMessage() {}

func (x *WebexConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebexConfig.ProtoReflect.Descriptor instead.
func (*WebexConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{39}
}

func (x *WebexConfig) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *WebexConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *WebexConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *WebexConfig) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// OAuth 2.0 + PKCE. Backend generates code_verifier/code_challenge
// and stores verifier in OAuth session (not in proto).
type XConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OAuth 2.0+PKCE mode
	ClientId     string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	// Static mode: app-only bearer token (read-only, no user context)
	BearerToken   string `protobuf:"bytes,3,opt,name=bearer_token,json=bearerToken" json:"bearer_token,omitempty"`
	Username      string `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XConfig) Reset() {
	*x = XConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XConfig) ProtoMessage() {}

func (x *XConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XConfig.ProtoReflect.Descriptor instead.
func (*XConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{40}
}

func (x *XConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *XConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *XConfig) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

func (x *XConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ZoomChatConfig struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ClientId     string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	// Server-to-Server (S2S) mode: provide account_id → direct, ACTIVE immediately.
	// User OAuth mode: omit account_id → AUTHORIZING + redirect.
	AccountId     string `protobuf:"bytes,3,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	UserEmail     string `protobuf:"bytes,4,opt,name=user_email,json=userEmail" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoomChatConfig) Reset() {
	*x = ZoomChatConfig{}
	mi := &file_outbox_v1_connector_config_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoomChatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoomChatConfig) ProtoMessage() {}

func (x *ZoomChatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_config_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoomChatConfig.ProtoReflect.Descriptor instead.
func (*ZoomChatConfig) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_config_proto_rawDescGZIP(), []int{41}
}

func (x *ZoomChatConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ZoomChatConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *ZoomChatConfig) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ZoomChatConfig) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

var File_outbox_v1_connector_config_proto protoreflect.FileDescriptor

const file_outbox_v1_connector_config_proto_rawDesc = "" +
	"\n" +
	" outbox/v1/connector_config.proto\x12\toutbox.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\"m\n" +
	"\x11ActivityPubConfig\x12(\n" +
	"\tactor_url\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\x88\x01\x01R\bactorUrl\x12.\n" +
	"\vprivate_key\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\n" +
	"privateKey\"\x84\x01\n" +
	"\n" +
	"ApnsConfig\x12!\n" +
	"\x06key_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05keyId\x12#\n" +
	"\ateam_id\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x06teamId\x12.\n" +
	"\vprivate_key\x18\x03 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\n" +
	"privateKey\"^\n" +
	"\x13AppleMessagesConfig\x12+\n" +
	"\vbusiness_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"businessId\x12\x1a\n" +
	"\x06msp_id\x18\x02 \x01(\tB\x03\xe0A\x01R\x05mspId\"e\n" +
	"\rBlueskyConfig\x12\"\n" +
	"\x06handle\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x06handle\x120\n" +
	"\fapp_password\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\vappPassword\";\n" +
	"\rDiscordConfig\x12*\n" +
	"\tbot_token\x18\x01 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\bbotToken\"d\n" +
	"\vEmailConfig\x12&\n" +
	"\aapi_key\x18\x01 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\x06apiKey\x12-\n" +
	"\ffrom_address\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02`\x01R\vfromAddress\"J\n" +
	"\tFcmConfig\x12=\n" +
	"\x13service_account_key\x18\x01 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\x11serviceAccountKey\"`\n" +
	"\x0fFreshchatConfig\x12!\n" +
	"\x06app_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05appId\x12*\n" +
	"\tapi_token\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\bapiToken\"\r\n" +
	"\vInAppConfig\"t\n" +
	"\fMatrixConfig\x122\n" +
	"\x0ehomeserver_url\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\x88\x01\x01R\rhomeserverUrl\x120\n" +
	"\faccess_token\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\vaccessToken\"}\n" +
	"\n" +
	"MqttConfig\x12*\n" +
	"\n" +
	"broker_url\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\x88\x01\x01R\tbrokerUrl\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tB\x03\xe0A\x01R\busername\x12\"\n" +
	"\bpassword\x18\x03 \x01(\tB\x06\xe0A\x01\xe0A\x04R\bpassword\"J\n" +
	"\tRcsConfig\x12=\n" +
	"\x13service_account_key\x18\x01 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\x11serviceAccountKey\"_\n" +
	"\fSignalConfig\x12 \n" +
	"\x03url\x18\x01 \x01(\tB\x0e\xe0A\x02\xe0A\x04\xbaH\x05r\x03\x88\x01\x01R\x03url\x12-\n" +
	"\fphone_number\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\vphoneNumber\"\x93\x01\n" +
	"\tSmsConfig\x12+\n" +
	"\vaccount_sid\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"accountSid\x12,\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tauthToken\x12+\n" +
	"\vfrom_number\x18\x03 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"fromNumber\"<\n" +
	"\x0eTelegramConfig\x12*\n" +
	"\tbot_token\x18\x01 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\bbotToken\";\n" +
	"\vViberConfig\x12,\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tauthToken\"\x80\x01\n" +
	"\rWebPushConfig\x124\n" +
	"\x10vapid_public_key\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x0evapidPublicKey\x129\n" +
	"\x11vapid_private_key\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\x0fvapidPrivateKey\"\x83\x01\n" +
	"\n" +
	"XmppConfig\x12\"\n" +
	"\x06server\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x06server\x12&\n" +
	"\busername\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\busername\x12)\n" +
	"\bpassword\x18\x03 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\bpassword\"\x93\x01\n" +
	"\vTeamsConfig\x12'\n" +
	"\ttenant_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\btenantId\x12'\n" +
	"\tclient_id\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\bclientId\x122\n" +
	"\rclient_secret\x18\x03 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\fclientSecret\"\x84\x01\n" +
	"\fWechatConfig\x12!\n" +
	"\x06app_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05appId\x12,\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tappSecret\x12#\n" +
	"\x05token\x18\x03 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\x05token\"\x8e\x01\n" +
	"\rHubspotConfig\x12'\n" +
	"\tclient_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\bclientId\x122\n" +
	"\rclient_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\fclientSecret\x12 \n" +
	"\tportal_id\x18\x03 \x01(\tB\x03\xe0A\x03R\bportalId\"\x8d\x01\n" +
	"\x0eIntercomConfig\x12!\n" +
	"\x06app_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05appId\x12,\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tappSecret\x12*\n" +
	"\x0eworkspace_name\x18\x03 \x01(\tB\x03\xe0A\x03R\rworkspaceName\"\x95\x01\n" +
	"\x0eLinkedinConfig\x12'\n" +
	"\tclient_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\bclientId\x122\n" +
	"\rclient_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\fclientSecret\x12&\n" +
	"\fprofile_name\x18\x03 \x01(\tB\x03\xe0A\x03R\vprofileName\"m\n" +
	"\x0eLiveChatConfig\x12'\n" +
	"\tclient_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\bclientId\x122\n" +
	"\rclient_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\fclientSecret\"\x8c\x01\n" +
	"\fRedditConfig\x12'\n" +
	"\tclient_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\bclientId\x122\n" +
	"\rclient_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\fclientSecret\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tB\x03\xe0A\x03R\busername\"~\n" +
	"\rThreadsConfig\x12!\n" +
	"\x06app_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05appId\x12,\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tappSecret\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\tB\x03\xe0A\x03R\x06userId\"\x8b\x01\n" +
	"\fTiktokConfig\x12)\n" +
	"\n" +
	"client_key\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\tclientKey\x122\n" +
	"\rclient_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\fclientSecret\x12\x1c\n" +
	"\aopen_id\x18\x03 \x01(\tB\x03\xe0A\x03R\x06openId\"\x93\x01\n" +
	"\fTwitchConfig\x12'\n" +
	"\tclient_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\bclientId\x122\n" +
	"\rclient_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\fclientSecret\x12&\n" +
	"\fbot_username\x18\x03 \x01(\tB\x03\xe0A\x03R\vbotUsername\"w\n" +
	"\n" +
	"ZaloConfig\x12!\n" +
	"\x06app_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05appId\x12,\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tappSecret\x12\x18\n" +
	"\x05oa_id\x18\x03 \x01(\tB\x03\xe0A\x03R\x04oaId\"\xbe\x01\n" +
	"\rZendeskConfig\x12(\n" +
	"\tsubdomain\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\tsubdomain\x12'\n" +
	"\tclient_id\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\bclientId\x122\n" +
	"\rclient_secret\x18\x03 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\fclientSecret\x12&\n" +
	"\faccount_name\x18\x04 \x01(\tB\x03\xe0A\x03R\vaccountName\"\xb7\x01\n" +
	"\x0fInstagramConfig\x12!\n" +
	"\x06app_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05appId\x12,\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tappSecret\x12\x1c\n" +
	"\apage_id\x18\x03 \x01(\tB\x03\xe0A\x03R\x06pageId\x125\n" +
	"\x14instagram_account_id\x18\x04 \x01(\tB\x03\xe0A\x03R\x12instagramAccountId\"\xa2\x01\n" +
	"\x0fMessengerConfig\x12!\n" +
	"\x06app_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05appId\x12,\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tappSecret\x12\x1c\n" +
	"\apage_id\x18\x03 \x01(\tB\x03\xe0A\x03R\x06pageId\x12 \n" +
	"\tpage_name\x18\x04 \x01(\tB\x03\xe0A\x03R\bpageName\"\xe3\x01\n" +
	"\x0eWhatsAppConfig\x12!\n" +
	"\x06app_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05appId\x12,\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tappSecret\x12\x1c\n" +
	"\awaba_id\x18\x03 \x01(\tB\x03\xe0A\x03R\x06wabaId\x12+\n" +
	"\x0fphone_number_id\x18\x04 \x01(\tB\x03\xe0A\x03R\rphoneNumberId\x125\n" +
	"\x14display_phone_number\x18\x05 \x01(\tB\x03\xe0A\x03R\x12displayPhoneNumber\"\xe8\x02\n" +
	"\x10GoogleChatConfig\x126\n" +
	"\x13service_account_key\x18\x01 \x01(\tB\x06\xe0A\x01\xe0A\x04R\x11serviceAccountKey\x12 \n" +
	"\tclient_id\x18\x02 \x01(\tB\x03\xe0A\x01R\bclientId\x12+\n" +
	"\rclient_secret\x18\x03 \x01(\tB\x06\xe0A\x01\xe0A\x04R\fclientSecret\x12\x1e\n" +
	"\bspace_id\x18\x04 \x01(\tB\x03\xe0A\x03R\aspaceId:\xac\x01\xbaH\xa8\x01\x1a\xa5\x01\n" +
	"\x17google_chat_config_mode\x12Nprovide service_account_key (bot) or client_id+client_secret (OAuth), not both\x1a:(this.service_account_key != '') != (this.client_id != '')\"\xaa\x03\n" +
	"\x0fKakaoTalkConfig\x12'\n" +
	"\rbiz_client_id\x18\x01 \x01(\tB\x03\xe0A\x01R\vbizClientId\x122\n" +
	"\x11biz_client_secret\x18\x02 \x01(\tB\x06\xe0A\x01\xe0A\x04R\x0fbizClientSecret\x12%\n" +
	"\frest_api_key\x18\x03 \x01(\tB\x03\xe0A\x01R\n" +
	"restApiKey\x12+\n" +
	"\rclient_secret\x18\x04 \x01(\tB\x06\xe0A\x01\xe0A\x04R\fclientSecret\x12'\n" +
	"\rkakao_user_id\x18\x05 \x01(\tB\x03\xe0A\x03R\vkakaoUserId\x12&\n" +
	"\fchannel_name\x18\x06 \x01(\tB\x03\xe0A\x03R\vchannelName:\x94\x01\xbaH\x90\x01\x1a\x8d\x01\n" +
	"\x11kakao_config_mode\x12?provide biz credentials or personal OAuth credentials, not both\x1a7(this.biz_client_id != '') != (this.rest_api_key != '')\"\xa7\x01\n" +
	"\n" +
	"LarkConfig\x12!\n" +
	"\x06app_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05appId\x12,\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\tappSecret\x12\"\n" +
	"\n" +
	"user_oauth\x18\x03 \x01(\bB\x03\xe0A\x01R\tuserOauth\x12$\n" +
	"\vtenant_name\x18\x04 \x01(\tB\x03\xe0A\x03R\n" +
	"tenantName\"\xc6\x02\n" +
	"\n" +
	"LineConfig\x12+\n" +
	"\rchannel_token\x18\x01 \x01(\tB\x06\xe0A\x01\xe0A\x04R\fchannelToken\x124\n" +
	"\x0echannel_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\rchannelSecret\x12\"\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tB\x03\xe0A\x01R\tchannelId\x12\x1e\n" +
	"\bbot_name\x18\x04 \x01(\tB\x03\xe0A\x03R\abotName:\x90\x01\xbaH\x8c\x01\x1a\x89\x01\n" +
	"\x10line_config_mode\x12>provide channel_token (direct) or channel_id (OAuth), not both\x1a5(this.channel_token != '') != (this.channel_id != '')\"\xc1\x02\n" +
	"\x10MattermostConfig\x12\x1d\n" +
	"\x03url\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\x88\x01\x01R\x03url\x12#\n" +
	"\tbot_token\x18\x02 \x01(\tB\x06\xe0A\x01\xe0A\x04R\bbotToken\x12'\n" +
	"\vadmin_token\x18\x03 \x01(\tB\x06\xe0A\x01\xe0A\x04R\n" +
	"adminToken\x12&\n" +
	"\fbot_username\x18\x04 \x01(\tB\x03\xe0A\x03R\vbotUsername:\x97\x01\xbaH\x93\x01\x1a\x90\x01\n" +
	"\x16mattermost_config_mode\x12Bprovide bot_token (direct) or admin_token (programmatic), not both\x1a2(this.bot_token != '') != (this.admin_token != '')\"\x8f\x03\n" +
	"\vSlackConfig\x12#\n" +
	"\tbot_token\x18\x01 \x01(\tB\x06\xe0A\x01\xe0A\x04R\bbotToken\x12-\n" +
	"\x0esigning_secret\x18\x02 \x01(\tB\x06\xe0A\x01\xe0A\x04R\rsigningSecret\x12 \n" +
	"\tclient_id\x18\x03 \x01(\tB\x03\xe0A\x01R\bclientId\x12+\n" +
	"\rclient_secret\x18\x04 \x01(\tB\x06\xe0A\x01\xe0A\x04R\fclientSecret\x12 \n" +
	"\tteam_name\x18\x05 \x01(\tB\x03\xe0A\x03R\bteamName\x12#\n" +
	"\vbot_user_id\x18\x06 \x01(\tB\x03\xe0A\x03R\tbotUserId:\x95\x01\xbaH\x91\x01\x1a\x8e\x01\n" +
	"\x11slack_config_mode\x12Gprovide bot_token (direct) or client_id+client_secret (OAuth), not both\x1a0(this.bot_token != '') != (this.client_id != '')\"\xc1\x02\n" +
	"\vWebexConfig\x12#\n" +
	"\tbot_token\x18\x01 \x01(\tB\x06\xe0A\x01\xe0A\x04R\bbotToken\x12 \n" +
	"\tclient_id\x18\x02 \x01(\tB\x03\xe0A\x01R\bclientId\x12+\n" +
	"\rclient_secret\x18\x03 \x01(\tB\x06\xe0A\x01\xe0A\x04R\fclientSecret\x12&\n" +
	"\fdisplay_name\x18\x04 \x01(\tB\x03\xe0A\x03R\vdisplayName:\x95\x01\xbaH\x91\x01\x1a\x8e\x01\n" +
	"\x11webex_config_mode\x12Gprovide bot_token (direct) or client_id+client_secret (OAuth), not both\x1a0(this.bot_token != '') != (this.client_id != '')\"\xd0\x02\n" +
	"\aXConfig\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tB\x03\xe0A\x01R\bclientId\x12+\n" +
	"\rclient_secret\x18\x02 \x01(\tB\x06\xe0A\x01\xe0A\x04R\fclientSecret\x12)\n" +
	"\fbearer_token\x18\x03 \x01(\tB\x06\xe0A\x01\xe0A\x04R\vbearerToken\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tB\x03\xe0A\x03R\busername:\xa9\x01\xbaH\xa5\x01\x1a\xa2\x01\n" +
	"\x16x_config_auth_required\x12Sprovide bearer_token (static) or client_id+client_secret (OAuth 2.0+PKCE), not both\x1a3(this.bearer_token != '') != (this.client_id != '')\"\xb5\x01\n" +
	"\x0eZoomChatConfig\x12'\n" +
	"\tclient_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\bclientId\x122\n" +
	"\rclient_secret\x18\x02 \x01(\tB\r\xe0A\x02\xe0A\x04\xbaH\x04r\x02\x10\x01R\fclientSecret\x12\"\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tB\x03\xe0A\x01R\taccountId\x12\"\n" +
	"\n" +
	"user_email\x18\x04 \x01(\tB\x03\xe0A\x03R\tuserEmailBPZIgithub.com/getoutbox/outbox-internal/go/outbox-api/gen/outbox/v1;outboxv1\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_outbox_v1_connector_config_proto_rawDescOnce sync.Once
	file_outbox_v1_connector_config_proto_rawDescData []byte
)

func file_outbox_v1_connector_config_proto_rawDescGZIP() []byte {
	file_outbox_v1_connector_config_proto_rawDescOnce.Do(func() {
		file_outbox_v1_connector_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outbox_v1_connector_config_proto_rawDesc), len(file_outbox_v1_connector_config_proto_rawDesc)))
	})
	return file_outbox_v1_connector_config_proto_rawDescData
}

var file_outbox_v1_connector_config_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_outbox_v1_connector_config_proto_goTypes = []any{
	(*ActivityPubConfig)(nil),   // 0: outbox.v1.ActivityPubConfig
	(*ApnsConfig)(nil),          // 1: outbox.v1.ApnsConfig
	(*AppleMessagesConfig)(nil), // 2: outbox.v1.AppleMessagesConfig
	(*BlueskyConfig)(nil),       // 3: outbox.v1.BlueskyConfig
	(*DiscordConfig)(nil),       // 4: outbox.v1.DiscordConfig
	(*EmailConfig)(nil),         // 5: outbox.v1.EmailConfig
	(*FcmConfig)(nil),           // 6: outbox.v1.FcmConfig
	(*FreshchatConfig)(nil),     // 7: outbox.v1.FreshchatConfig
	(*InAppConfig)(nil),         // 8: outbox.v1.InAppConfig
	(*MatrixConfig)(nil),        // 9: outbox.v1.MatrixConfig
	(*MqttConfig)(nil),          // 10: outbox.v1.MqttConfig
	(*RcsConfig)(nil),           // 11: outbox.v1.RcsConfig
	(*SignalConfig)(nil),        // 12: outbox.v1.SignalConfig
	(*SmsConfig)(nil),           // 13: outbox.v1.SmsConfig
	(*TelegramConfig)(nil),      // 14: outbox.v1.TelegramConfig
	(*ViberConfig)(nil),         // 15: outbox.v1.ViberConfig
	(*WebPushConfig)(nil),       // 16: outbox.v1.WebPushConfig
	(*XmppConfig)(nil),          // 17: outbox.v1.XmppConfig
	(*TeamsConfig)(nil),         // 18: outbox.v1.TeamsConfig
	(*WechatConfig)(nil),        // 19: outbox.v1.WechatConfig
	(*HubspotConfig)(nil),       // 20: outbox.v1.HubspotConfig
	(*IntercomConfig)(nil),      // 21: outbox.v1.IntercomConfig
	(*LinkedinConfig)(nil),      // 22: outbox.v1.LinkedinConfig
	(*LiveChatConfig)(nil),      // 23: outbox.v1.LiveChatConfig
	(*RedditConfig)(nil),        // 24: outbox.v1.RedditConfig
	(*ThreadsConfig)(nil),       // 25: outbox.v1.ThreadsConfig
	(*TiktokConfig)(nil),        // 26: outbox.v1.TiktokConfig
	(*TwitchConfig)(nil),        // 27: outbox.v1.TwitchConfig
	(*ZaloConfig)(nil),          // 28: outbox.v1.ZaloConfig
	(*ZendeskConfig)(nil),       // 29: outbox.v1.ZendeskConfig
	(*InstagramConfig)(nil),     // 30: outbox.v1.InstagramConfig
	(*MessengerConfig)(nil),     // 31: outbox.v1.MessengerConfig
	(*WhatsAppConfig)(nil),      // 32: outbox.v1.WhatsAppConfig
	(*GoogleChatConfig)(nil),    // 33: outbox.v1.GoogleChatConfig
	(*KakaoTalkConfig)(nil),     // 34: outbox.v1.KakaoTalkConfig
	(*LarkConfig)(nil),          // 35: outbox.v1.LarkConfig
	(*LineConfig)(nil),          // 36: outbox.v1.LineConfig
	(*MattermostConfig)(nil),    // 37: outbox.v1.MattermostConfig
	(*SlackConfig)(nil),         // 38: outbox.v1.SlackConfig
	(*WebexConfig)(nil),         // 39: outbox.v1.WebexConfig
	(*XConfig)(nil),             // 40: outbox.v1.XConfig
	(*ZoomChatConfig)(nil),      // 41: outbox.v1.ZoomChatConfig
}
var file_outbox_v1_connector_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_outbox_v1_connector_config_proto_init() }
func file_outbox_v1_connector_config_proto_init() {
	if File_outbox_v1_connector_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outbox_v1_connector_config_proto_rawDesc), len(file_outbox_v1_connector_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outbox_v1_connector_config_proto_goTypes,
		DependencyIndexes: file_outbox_v1_connector_config_proto_depIdxs,
		MessageInfos:      file_outbox_v1_connector_config_proto_msgTypes,
	}.Build()
	File_outbox_v1_connector_config_proto = out.File
	file_outbox_v1_connector_config_proto_goTypes = nil
	file_outbox_v1_connector_config_proto_depIdxs = nil
}
