// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: outbox/v1/connector.proto

package outboxv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Connector_State int32

const (
	Connector_STATE_UNSPECIFIED Connector_State = 0
	Connector_STATE_ACTIVE      Connector_State = 1
	Connector_STATE_INACTIVE    Connector_State = 2
	Connector_STATE_AUTHORIZING Connector_State = 3
	Connector_STATE_ERROR       Connector_State = 4
)

// Enum value maps for Connector_State.
var (
	Connector_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_ACTIVE",
		2: "STATE_INACTIVE",
		3: "STATE_AUTHORIZING",
		4: "STATE_ERROR",
	}
	Connector_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_ACTIVE":      1,
		"STATE_INACTIVE":    2,
		"STATE_AUTHORIZING": 3,
		"STATE_ERROR":       4,
	}
)

func (x Connector_State) Enum() *Connector_State {
	p := new(Connector_State)
	*p = x
	return p
}

func (x Connector_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Connector_State) Descriptor() protoreflect.EnumDescriptor {
	return file_outbox_v1_connector_proto_enumTypes[0].Descriptor()
}

func (Connector_State) Type() protoreflect.EnumType {
	return &file_outbox_v1_connector_proto_enumTypes[0]
}

func (x Connector_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Connector_State.Descriptor instead.
func (Connector_State) EnumDescriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{0, 0}
}

type Connector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Format: connectors/{connector}
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The account identity this connector operates as in messaging.
	// Populated by the backend after creation (static) or OAuth completion.
	Account *Account        `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	State   Connector_State `protobuf:"varint,3,opt,name=state,enum=outbox.v1.Connector_State" json:"state,omitempty"`
	// Arbitrary string labels for filtering and organization. No format constraints.
	Tags       []string               `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	// Human-readable error detail when state is ERROR.
	ErrorMessage string `protobuf:"bytes,7,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// Channel-specific configuration. The selected branch identifies the channel type.
	//
	// Types that are valid to be assigned to ChannelConfig:
	//
	//	*Connector_ActivityPub
	//	*Connector_Apns
	//	*Connector_AppleMessages
	//	*Connector_Bluesky
	//	*Connector_Discord
	//	*Connector_Email
	//	*Connector_Fcm
	//	*Connector_Freshchat
	//	*Connector_GoogleChat
	//	*Connector_Hubspot
	//	*Connector_InApp
	//	*Connector_Instagram
	//	*Connector_Intercom
	//	*Connector_KakaoTalk
	//	*Connector_Lark
	//	*Connector_Line
	//	*Connector_Linkedin
	//	*Connector_LiveChat
	//	*Connector_Matrix
	//	*Connector_Mattermost
	//	*Connector_Messenger
	//	*Connector_Mqtt
	//	*Connector_Rcs
	//	*Connector_Reddit
	//	*Connector_Signal
	//	*Connector_Slack
	//	*Connector_Sms
	//	*Connector_Teams
	//	*Connector_Telegram
	//	*Connector_Threads
	//	*Connector_Tiktok
	//	*Connector_Twitch
	//	*Connector_Viber
	//	*Connector_Webex
	//	*Connector_WebPush
	//	*Connector_Wechat
	//	*Connector_Whatsapp
	//	*Connector_X
	//	*Connector_Xmpp
	//	*Connector_Zalo
	//	*Connector_Zendesk
	//	*Connector_ZoomChat
	ChannelConfig isConnector_ChannelConfig `protobuf_oneof:"channel_config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connector) Reset() {
	*x = Connector{}
	mi := &file_outbox_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connector) ProtoMessage() {}

func (x *Connector) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connector.ProtoReflect.Descriptor instead.
func (*Connector) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *Connector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Connector) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Connector) GetState() Connector_State {
	if x != nil {
		return x.State
	}
	return Connector_STATE_UNSPECIFIED
}

func (x *Connector) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Connector) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Connector) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Connector) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Connector) GetChannelConfig() isConnector_ChannelConfig {
	if x != nil {
		return x.ChannelConfig
	}
	return nil
}

func (x *Connector) GetActivityPub() *ActivityPubConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_ActivityPub); ok {
			return x.ActivityPub
		}
	}
	return nil
}

func (x *Connector) GetApns() *ApnsConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Apns); ok {
			return x.Apns
		}
	}
	return nil
}

func (x *Connector) GetAppleMessages() *AppleMessagesConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_AppleMessages); ok {
			return x.AppleMessages
		}
	}
	return nil
}

func (x *Connector) GetBluesky() *BlueskyConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Bluesky); ok {
			return x.Bluesky
		}
	}
	return nil
}

func (x *Connector) GetDiscord() *DiscordConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Discord); ok {
			return x.Discord
		}
	}
	return nil
}

func (x *Connector) GetEmail() *EmailConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Email); ok {
			return x.Email
		}
	}
	return nil
}

func (x *Connector) GetFcm() *FcmConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Fcm); ok {
			return x.Fcm
		}
	}
	return nil
}

func (x *Connector) GetFreshchat() *FreshchatConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Freshchat); ok {
			return x.Freshchat
		}
	}
	return nil
}

func (x *Connector) GetGoogleChat() *GoogleChatConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_GoogleChat); ok {
			return x.GoogleChat
		}
	}
	return nil
}

func (x *Connector) GetHubspot() *HubspotConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Hubspot); ok {
			return x.Hubspot
		}
	}
	return nil
}

func (x *Connector) GetInApp() *InAppConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_InApp); ok {
			return x.InApp
		}
	}
	return nil
}

func (x *Connector) GetInstagram() *InstagramConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Instagram); ok {
			return x.Instagram
		}
	}
	return nil
}

func (x *Connector) GetIntercom() *IntercomConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Intercom); ok {
			return x.Intercom
		}
	}
	return nil
}

func (x *Connector) GetKakaoTalk() *KakaoTalkConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_KakaoTalk); ok {
			return x.KakaoTalk
		}
	}
	return nil
}

func (x *Connector) GetLark() *LarkConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Lark); ok {
			return x.Lark
		}
	}
	return nil
}

func (x *Connector) GetLine() *LineConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *Connector) GetLinkedin() *LinkedinConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Linkedin); ok {
			return x.Linkedin
		}
	}
	return nil
}

func (x *Connector) GetLiveChat() *LiveChatConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_LiveChat); ok {
			return x.LiveChat
		}
	}
	return nil
}

func (x *Connector) GetMatrix() *MatrixConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Matrix); ok {
			return x.Matrix
		}
	}
	return nil
}

func (x *Connector) GetMattermost() *MattermostConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Mattermost); ok {
			return x.Mattermost
		}
	}
	return nil
}

func (x *Connector) GetMessenger() *MessengerConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Messenger); ok {
			return x.Messenger
		}
	}
	return nil
}

func (x *Connector) GetMqtt() *MqttConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Mqtt); ok {
			return x.Mqtt
		}
	}
	return nil
}

func (x *Connector) GetRcs() *RcsConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Rcs); ok {
			return x.Rcs
		}
	}
	return nil
}

func (x *Connector) GetReddit() *RedditConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Reddit); ok {
			return x.Reddit
		}
	}
	return nil
}

func (x *Connector) GetSignal() *SignalConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *Connector) GetSlack() *SlackConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Slack); ok {
			return x.Slack
		}
	}
	return nil
}

func (x *Connector) GetSms() *SmsConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Sms); ok {
			return x.Sms
		}
	}
	return nil
}

func (x *Connector) GetTeams() *TeamsConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Teams); ok {
			return x.Teams
		}
	}
	return nil
}

func (x *Connector) GetTelegram() *TelegramConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Telegram); ok {
			return x.Telegram
		}
	}
	return nil
}

func (x *Connector) GetThreads() *ThreadsConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Threads); ok {
			return x.Threads
		}
	}
	return nil
}

func (x *Connector) GetTiktok() *TiktokConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Tiktok); ok {
			return x.Tiktok
		}
	}
	return nil
}

func (x *Connector) GetTwitch() *TwitchConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Twitch); ok {
			return x.Twitch
		}
	}
	return nil
}

func (x *Connector) GetViber() *ViberConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Viber); ok {
			return x.Viber
		}
	}
	return nil
}

func (x *Connector) GetWebex() *WebexConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Webex); ok {
			return x.Webex
		}
	}
	return nil
}

func (x *Connector) GetWebPush() *WebPushConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_WebPush); ok {
			return x.WebPush
		}
	}
	return nil
}

func (x *Connector) GetWechat() *WechatConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Wechat); ok {
			return x.Wechat
		}
	}
	return nil
}

func (x *Connector) GetWhatsapp() *WhatsAppConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Whatsapp); ok {
			return x.Whatsapp
		}
	}
	return nil
}

func (x *Connector) GetX() *XConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_X); ok {
			return x.X
		}
	}
	return nil
}

func (x *Connector) GetXmpp() *XmppConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Xmpp); ok {
			return x.Xmpp
		}
	}
	return nil
}

func (x *Connector) GetZalo() *ZaloConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Zalo); ok {
			return x.Zalo
		}
	}
	return nil
}

func (x *Connector) GetZendesk() *ZendeskConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_Zendesk); ok {
			return x.Zendesk
		}
	}
	return nil
}

func (x *Connector) GetZoomChat() *ZoomChatConfig {
	if x != nil {
		if x, ok := x.ChannelConfig.(*Connector_ZoomChat); ok {
			return x.ZoomChat
		}
	}
	return nil
}

type isConnector_ChannelConfig interface {
	isConnector_ChannelConfig()
}

type Connector_ActivityPub struct {
	ActivityPub *ActivityPubConfig `protobuf:"bytes,8,opt,name=activity_pub,json=activityPub,oneof"`
}

type Connector_Apns struct {
	Apns *ApnsConfig `protobuf:"bytes,9,opt,name=apns,oneof"`
}

type Connector_AppleMessages struct {
	AppleMessages *AppleMessagesConfig `protobuf:"bytes,10,opt,name=apple_messages,json=appleMessages,oneof"`
}

type Connector_Bluesky struct {
	Bluesky *BlueskyConfig `protobuf:"bytes,11,opt,name=bluesky,oneof"`
}

type Connector_Discord struct {
	Discord *DiscordConfig `protobuf:"bytes,12,opt,name=discord,oneof"`
}

type Connector_Email struct {
	Email *EmailConfig `protobuf:"bytes,13,opt,name=email,oneof"`
}

type Connector_Fcm struct {
	Fcm *FcmConfig `protobuf:"bytes,14,opt,name=fcm,oneof"`
}

type Connector_Freshchat struct {
	Freshchat *FreshchatConfig `protobuf:"bytes,15,opt,name=freshchat,oneof"`
}

type Connector_GoogleChat struct {
	GoogleChat *GoogleChatConfig `protobuf:"bytes,16,opt,name=google_chat,json=googleChat,oneof"`
}

type Connector_Hubspot struct {
	Hubspot *HubspotConfig `protobuf:"bytes,17,opt,name=hubspot,oneof"`
}

type Connector_InApp struct {
	InApp *InAppConfig `protobuf:"bytes,18,opt,name=in_app,json=inApp,oneof"`
}

type Connector_Instagram struct {
	Instagram *InstagramConfig `protobuf:"bytes,19,opt,name=instagram,oneof"`
}

type Connector_Intercom struct {
	Intercom *IntercomConfig `protobuf:"bytes,20,opt,name=intercom,oneof"`
}

type Connector_KakaoTalk struct {
	KakaoTalk *KakaoTalkConfig `protobuf:"bytes,21,opt,name=kakao_talk,json=kakaoTalk,oneof"`
}

type Connector_Lark struct {
	Lark *LarkConfig `protobuf:"bytes,22,opt,name=lark,oneof"`
}

type Connector_Line struct {
	Line *LineConfig `protobuf:"bytes,23,opt,name=line,oneof"`
}

type Connector_Linkedin struct {
	Linkedin *LinkedinConfig `protobuf:"bytes,24,opt,name=linkedin,oneof"`
}

type Connector_LiveChat struct {
	LiveChat *LiveChatConfig `protobuf:"bytes,25,opt,name=live_chat,json=liveChat,oneof"`
}

type Connector_Matrix struct {
	Matrix *MatrixConfig `protobuf:"bytes,26,opt,name=matrix,oneof"`
}

type Connector_Mattermost struct {
	Mattermost *MattermostConfig `protobuf:"bytes,27,opt,name=mattermost,oneof"`
}

type Connector_Messenger struct {
	Messenger *MessengerConfig `protobuf:"bytes,28,opt,name=messenger,oneof"`
}

type Connector_Mqtt struct {
	Mqtt *MqttConfig `protobuf:"bytes,29,opt,name=mqtt,oneof"`
}

type Connector_Rcs struct {
	Rcs *RcsConfig `protobuf:"bytes,30,opt,name=rcs,oneof"`
}

type Connector_Reddit struct {
	Reddit *RedditConfig `protobuf:"bytes,31,opt,name=reddit,oneof"`
}

type Connector_Signal struct {
	Signal *SignalConfig `protobuf:"bytes,32,opt,name=signal,oneof"`
}

type Connector_Slack struct {
	Slack *SlackConfig `protobuf:"bytes,33,opt,name=slack,oneof"`
}

type Connector_Sms struct {
	Sms *SmsConfig `protobuf:"bytes,34,opt,name=sms,oneof"`
}

type Connector_Teams struct {
	Teams *TeamsConfig `protobuf:"bytes,35,opt,name=teams,oneof"`
}

type Connector_Telegram struct {
	Telegram *TelegramConfig `protobuf:"bytes,36,opt,name=telegram,oneof"`
}

type Connector_Threads struct {
	Threads *ThreadsConfig `protobuf:"bytes,37,opt,name=threads,oneof"`
}

type Connector_Tiktok struct {
	Tiktok *TiktokConfig `protobuf:"bytes,38,opt,name=tiktok,oneof"`
}

type Connector_Twitch struct {
	Twitch *TwitchConfig `protobuf:"bytes,39,opt,name=twitch,oneof"`
}

type Connector_Viber struct {
	Viber *ViberConfig `protobuf:"bytes,40,opt,name=viber,oneof"`
}

type Connector_Webex struct {
	Webex *WebexConfig `protobuf:"bytes,41,opt,name=webex,oneof"`
}

type Connector_WebPush struct {
	WebPush *WebPushConfig `protobuf:"bytes,42,opt,name=web_push,json=webPush,oneof"`
}

type Connector_Wechat struct {
	Wechat *WechatConfig `protobuf:"bytes,43,opt,name=wechat,oneof"`
}

type Connector_Whatsapp struct {
	Whatsapp *WhatsAppConfig `protobuf:"bytes,44,opt,name=whatsapp,oneof"`
}

type Connector_X struct {
	X *XConfig `protobuf:"bytes,45,opt,name=x,oneof"`
}

type Connector_Xmpp struct {
	Xmpp *XmppConfig `protobuf:"bytes,46,opt,name=xmpp,oneof"`
}

type Connector_Zalo struct {
	Zalo *ZaloConfig `protobuf:"bytes,47,opt,name=zalo,oneof"`
}

type Connector_Zendesk struct {
	Zendesk *ZendeskConfig `protobuf:"bytes,48,opt,name=zendesk,oneof"`
}

type Connector_ZoomChat struct {
	ZoomChat *ZoomChatConfig `protobuf:"bytes,49,opt,name=zoom_chat,json=zoomChat,oneof"`
}

func (*Connector_ActivityPub) isConnector_ChannelConfig() {}

func (*Connector_Apns) isConnector_ChannelConfig() {}

func (*Connector_AppleMessages) isConnector_ChannelConfig() {}

func (*Connector_Bluesky) isConnector_ChannelConfig() {}

func (*Connector_Discord) isConnector_ChannelConfig() {}

func (*Connector_Email) isConnector_ChannelConfig() {}

func (*Connector_Fcm) isConnector_ChannelConfig() {}

func (*Connector_Freshchat) isConnector_ChannelConfig() {}

func (*Connector_GoogleChat) isConnector_ChannelConfig() {}

func (*Connector_Hubspot) isConnector_ChannelConfig() {}

func (*Connector_InApp) isConnector_ChannelConfig() {}

func (*Connector_Instagram) isConnector_ChannelConfig() {}

func (*Connector_Intercom) isConnector_ChannelConfig() {}

func (*Connector_KakaoTalk) isConnector_ChannelConfig() {}

func (*Connector_Lark) isConnector_ChannelConfig() {}

func (*Connector_Line) isConnector_ChannelConfig() {}

func (*Connector_Linkedin) isConnector_ChannelConfig() {}

func (*Connector_LiveChat) isConnector_ChannelConfig() {}

func (*Connector_Matrix) isConnector_ChannelConfig() {}

func (*Connector_Mattermost) isConnector_ChannelConfig() {}

func (*Connector_Messenger) isConnector_ChannelConfig() {}

func (*Connector_Mqtt) isConnector_ChannelConfig() {}

func (*Connector_Rcs) isConnector_ChannelConfig() {}

func (*Connector_Reddit) isConnector_ChannelConfig() {}

func (*Connector_Signal) isConnector_ChannelConfig() {}

func (*Connector_Slack) isConnector_ChannelConfig() {}

func (*Connector_Sms) isConnector_ChannelConfig() {}

func (*Connector_Teams) isConnector_ChannelConfig() {}

func (*Connector_Telegram) isConnector_ChannelConfig() {}

func (*Connector_Threads) isConnector_ChannelConfig() {}

func (*Connector_Tiktok) isConnector_ChannelConfig() {}

func (*Connector_Twitch) isConnector_ChannelConfig() {}

func (*Connector_Viber) isConnector_ChannelConfig() {}

func (*Connector_Webex) isConnector_ChannelConfig() {}

func (*Connector_WebPush) isConnector_ChannelConfig() {}

func (*Connector_Wechat) isConnector_ChannelConfig() {}

func (*Connector_Whatsapp) isConnector_ChannelConfig() {}

func (*Connector_X) isConnector_ChannelConfig() {}

func (*Connector_Xmpp) isConnector_ChannelConfig() {}

func (*Connector_Zalo) isConnector_ChannelConfig() {}

func (*Connector_Zendesk) isConnector_ChannelConfig() {}

func (*Connector_ZoomChat) isConnector_ChannelConfig() {}

type CreateConnectorRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Connector *Connector             `protobuf:"bytes,1,opt,name=connector" json:"connector,omitempty"`
	// Client-assigned idempotency token (AIP-155). Repeat requests with the same
	// request_id return the same connector without creating a duplicate.
	// Must be a UUID v4.
	RequestId     string `protobuf:"bytes,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnectorRequest) Reset() {
	*x = CreateConnectorRequest{}
	mi := &file_outbox_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnectorRequest) ProtoMessage() {}

func (x *CreateConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnectorRequest.ProtoReflect.Descriptor instead.
func (*CreateConnectorRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConnectorRequest) GetConnector() *Connector {
	if x != nil {
		return x.Connector
	}
	return nil
}

func (x *CreateConnectorRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateConnectorResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Connector *Connector             `protobuf:"bytes,1,opt,name=connector" json:"connector,omitempty"`
	// Present when the channel requires OAuth authorization.
	// Developer must redirect to this URL to complete setup.
	// Empty for direct-creation channels.
	AuthorizationUrl string `protobuf:"bytes,2,opt,name=authorization_url,json=authorizationUrl" json:"authorization_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateConnectorResponse) Reset() {
	*x = CreateConnectorResponse{}
	mi := &file_outbox_v1_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnectorResponse) ProtoMessage() {}

func (x *CreateConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnectorResponse.ProtoReflect.Descriptor instead.
func (*CreateConnectorResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{2}
}

func (x *CreateConnectorResponse) GetConnector() *Connector {
	if x != nil {
		return x.Connector
	}
	return nil
}

func (x *CreateConnectorResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

type GetConnectorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Format: connectors/{connector}
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectorRequest) Reset() {
	*x = GetConnectorRequest{}
	mi := &file_outbox_v1_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorRequest) ProtoMessage() {}

func (x *GetConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorRequest.ProtoReflect.Descriptor instead.
func (*GetConnectorRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{3}
}

func (x *GetConnectorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *Connector             `protobuf:"bytes,1,opt,name=connector" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectorResponse) Reset() {
	*x = GetConnectorResponse{}
	mi := &file_outbox_v1_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorResponse) ProtoMessage() {}

func (x *GetConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorResponse.ProtoReflect.Descriptor instead.
func (*GetConnectorResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{4}
}

func (x *GetConnectorResponse) GetConnector() *Connector {
	if x != nil {
		return x.Connector
	}
	return nil
}

type ListConnectorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of connectors to return (0–1000). Server defaults to 50 when 0 or unset.
	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	// CEL filter expression (AIP-160).
	// Example: `state == "STATE_ACTIVE"`
	Filter string `protobuf:"bytes,3,opt,name=filter" json:"filter,omitempty"`
	// Comma-separated fields to order by with optional " desc" suffix (AIP-132).
	// Example: "create_time desc"
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsRequest) Reset() {
	*x = ListConnectorsRequest{}
	mi := &file_outbox_v1_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsRequest) ProtoMessage() {}

func (x *ListConnectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectorsRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{5}
}

func (x *ListConnectorsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConnectorsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListConnectorsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListConnectorsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListConnectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connectors    []*Connector           `protobuf:"bytes,1,rep,name=connectors" json:"connectors,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	// Total number of connectors matching the request filter, across all pages.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsResponse) Reset() {
	*x = ListConnectorsResponse{}
	mi := &file_outbox_v1_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsResponse) ProtoMessage() {}

func (x *ListConnectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectorsResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{6}
}

func (x *ListConnectorsResponse) GetConnectors() []*Connector {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *ListConnectorsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListConnectorsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type UpdateConnectorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The connector to update. The name field identifies the resource.
	Connector     *Connector             `protobuf:"bytes,1,opt,name=connector" json:"connector,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConnectorRequest) Reset() {
	*x = UpdateConnectorRequest{}
	mi := &file_outbox_v1_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConnectorRequest) ProtoMessage() {}

func (x *UpdateConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConnectorRequest.ProtoReflect.Descriptor instead.
func (*UpdateConnectorRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateConnectorRequest) GetConnector() *Connector {
	if x != nil {
		return x.Connector
	}
	return nil
}

func (x *UpdateConnectorRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *Connector             `protobuf:"bytes,1,opt,name=connector" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConnectorResponse) Reset() {
	*x = UpdateConnectorResponse{}
	mi := &file_outbox_v1_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConnectorResponse) ProtoMessage() {}

func (x *UpdateConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConnectorResponse.ProtoReflect.Descriptor instead.
func (*UpdateConnectorResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateConnectorResponse) GetConnector() *Connector {
	if x != nil {
		return x.Connector
	}
	return nil
}

type DeleteConnectorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Format: connectors/{connector}
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnectorRequest) Reset() {
	*x = DeleteConnectorRequest{}
	mi := &file_outbox_v1_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectorRequest) ProtoMessage() {}

func (x *DeleteConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectorRequest.ProtoReflect.Descriptor instead.
func (*DeleteConnectorRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteConnectorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Empty response returned by DeleteConnector. Intentionally empty per AIP-135.
type DeleteConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnectorResponse) Reset() {
	*x = DeleteConnectorResponse{}
	mi := &file_outbox_v1_connector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectorResponse) ProtoMessage() {}

func (x *DeleteConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectorResponse.ProtoReflect.Descriptor instead.
func (*DeleteConnectorResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{10}
}

// Transition a connector to STATE_ACTIVE. No-op if already active.
// Returns FAILED_PRECONDITION if the connector is in AUTHORIZING state.
type ActivateConnectorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Format: connectors/{connector}
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateConnectorRequest) Reset() {
	*x = ActivateConnectorRequest{}
	mi := &file_outbox_v1_connector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateConnectorRequest) ProtoMessage() {}

func (x *ActivateConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateConnectorRequest.ProtoReflect.Descriptor instead.
func (*ActivateConnectorRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{11}
}

func (x *ActivateConnectorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ActivateConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *Connector             `protobuf:"bytes,1,opt,name=connector" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateConnectorResponse) Reset() {
	*x = ActivateConnectorResponse{}
	mi := &file_outbox_v1_connector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateConnectorResponse) ProtoMessage() {}

func (x *ActivateConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateConnectorResponse.ProtoReflect.Descriptor instead.
func (*ActivateConnectorResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{12}
}

func (x *ActivateConnectorResponse) GetConnector() *Connector {
	if x != nil {
		return x.Connector
	}
	return nil
}

// Transition a connector to STATE_INACTIVE. No-op if already inactive.
// Returns FAILED_PRECONDITION if the connector is in AUTHORIZING state.
type DeactivateConnectorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Format: connectors/{connector}
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateConnectorRequest) Reset() {
	*x = DeactivateConnectorRequest{}
	mi := &file_outbox_v1_connector_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateConnectorRequest) ProtoMessage() {}

func (x *DeactivateConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateConnectorRequest.ProtoReflect.Descriptor instead.
func (*DeactivateConnectorRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{13}
}

func (x *DeactivateConnectorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeactivateConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *Connector             `protobuf:"bytes,1,opt,name=connector" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateConnectorResponse) Reset() {
	*x = DeactivateConnectorResponse{}
	mi := &file_outbox_v1_connector_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateConnectorResponse) ProtoMessage() {}

func (x *DeactivateConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateConnectorResponse.ProtoReflect.Descriptor instead.
func (*DeactivateConnectorResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{14}
}

func (x *DeactivateConnectorResponse) GetConnector() *Connector {
	if x != nil {
		return x.Connector
	}
	return nil
}

// Re-trigger OAuth for an existing connector.
// Returns FAILED_PRECONDITION for static-credential channels.
// Callable from ERROR, ACTIVE, or INACTIVE states.
type ReauthorizeConnectorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name. Format: connectors/{connector}
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReauthorizeConnectorRequest) Reset() {
	*x = ReauthorizeConnectorRequest{}
	mi := &file_outbox_v1_connector_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReauthorizeConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReauthorizeConnectorRequest) ProtoMessage() {}

func (x *ReauthorizeConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReauthorizeConnectorRequest.ProtoReflect.Descriptor instead.
func (*ReauthorizeConnectorRequest) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{15}
}

func (x *ReauthorizeConnectorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReauthorizeConnectorResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl" json:"authorization_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReauthorizeConnectorResponse) Reset() {
	*x = ReauthorizeConnectorResponse{}
	mi := &file_outbox_v1_connector_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReauthorizeConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReauthorizeConnectorResponse) ProtoMessage() {}

func (x *ReauthorizeConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_v1_connector_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReauthorizeConnectorResponse.ProtoReflect.Descriptor instead.
func (*ReauthorizeConnectorResponse) Descriptor() ([]byte, []int) {
	return file_outbox_v1_connector_proto_rawDescGZIP(), []int{16}
}

func (x *ReauthorizeConnectorResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

var File_outbox_v1_connector_proto protoreflect.FileDescriptor

const file_outbox_v1_connector_proto_rawDesc = "" +
	"\n" +
	"\x19outbox/v1/connector.proto\x12\toutbox.v1\x1a\x1bbuf/validate/validate.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/field_info.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17outbox/v1/account.proto\x1a outbox/v1/connector_config.proto\"\x95\x17\n" +
	"\tConnector\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x121\n" +
	"\aaccount\x18\x02 \x01(\v2\x12.outbox.v1.AccountB\x03\xe0A\x03R\aaccount\x125\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1a.outbox.v1.Connector.StateB\x03\xe0A\x03R\x05state\x12\x17\n" +
	"\x04tags\x18\x04 \x03(\tB\x03\xe0A\x01R\x04tags\x12@\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12(\n" +
	"\rerror_message\x18\a \x01(\tB\x03\xe0A\x03R\ferrorMessage\x12F\n" +
	"\factivity_pub\x18\b \x01(\v2\x1c.outbox.v1.ActivityPubConfigB\x03\xe0A\x01H\x00R\vactivityPub\x120\n" +
	"\x04apns\x18\t \x01(\v2\x15.outbox.v1.ApnsConfigB\x03\xe0A\x01H\x00R\x04apns\x12L\n" +
	"\x0eapple_messages\x18\n" +
	" \x01(\v2\x1e.outbox.v1.AppleMessagesConfigB\x03\xe0A\x01H\x00R\rappleMessages\x129\n" +
	"\abluesky\x18\v \x01(\v2\x18.outbox.v1.BlueskyConfigB\x03\xe0A\x01H\x00R\abluesky\x129\n" +
	"\adiscord\x18\f \x01(\v2\x18.outbox.v1.DiscordConfigB\x03\xe0A\x01H\x00R\adiscord\x123\n" +
	"\x05email\x18\r \x01(\v2\x16.outbox.v1.EmailConfigB\x03\xe0A\x01H\x00R\x05email\x12-\n" +
	"\x03fcm\x18\x0e \x01(\v2\x14.outbox.v1.FcmConfigB\x03\xe0A\x01H\x00R\x03fcm\x12?\n" +
	"\tfreshchat\x18\x0f \x01(\v2\x1a.outbox.v1.FreshchatConfigB\x03\xe0A\x01H\x00R\tfreshchat\x12C\n" +
	"\vgoogle_chat\x18\x10 \x01(\v2\x1b.outbox.v1.GoogleChatConfigB\x03\xe0A\x01H\x00R\n" +
	"googleChat\x129\n" +
	"\ahubspot\x18\x11 \x01(\v2\x18.outbox.v1.HubspotConfigB\x03\xe0A\x01H\x00R\ahubspot\x124\n" +
	"\x06in_app\x18\x12 \x01(\v2\x16.outbox.v1.InAppConfigB\x03\xe0A\x01H\x00R\x05inApp\x12?\n" +
	"\tinstagram\x18\x13 \x01(\v2\x1a.outbox.v1.InstagramConfigB\x03\xe0A\x01H\x00R\tinstagram\x12<\n" +
	"\bintercom\x18\x14 \x01(\v2\x19.outbox.v1.IntercomConfigB\x03\xe0A\x01H\x00R\bintercom\x12@\n" +
	"\n" +
	"kakao_talk\x18\x15 \x01(\v2\x1a.outbox.v1.KakaoTalkConfigB\x03\xe0A\x01H\x00R\tkakaoTalk\x120\n" +
	"\x04lark\x18\x16 \x01(\v2\x15.outbox.v1.LarkConfigB\x03\xe0A\x01H\x00R\x04lark\x120\n" +
	"\x04line\x18\x17 \x01(\v2\x15.outbox.v1.LineConfigB\x03\xe0A\x01H\x00R\x04line\x12<\n" +
	"\blinkedin\x18\x18 \x01(\v2\x19.outbox.v1.LinkedinConfigB\x03\xe0A\x01H\x00R\blinkedin\x12=\n" +
	"\tlive_chat\x18\x19 \x01(\v2\x19.outbox.v1.LiveChatConfigB\x03\xe0A\x01H\x00R\bliveChat\x126\n" +
	"\x06matrix\x18\x1a \x01(\v2\x17.outbox.v1.MatrixConfigB\x03\xe0A\x01H\x00R\x06matrix\x12B\n" +
	"\n" +
	"mattermost\x18\x1b \x01(\v2\x1b.outbox.v1.MattermostConfigB\x03\xe0A\x01H\x00R\n" +
	"mattermost\x12?\n" +
	"\tmessenger\x18\x1c \x01(\v2\x1a.outbox.v1.MessengerConfigB\x03\xe0A\x01H\x00R\tmessenger\x120\n" +
	"\x04mqtt\x18\x1d \x01(\v2\x15.outbox.v1.MqttConfigB\x03\xe0A\x01H\x00R\x04mqtt\x12-\n" +
	"\x03rcs\x18\x1e \x01(\v2\x14.outbox.v1.RcsConfigB\x03\xe0A\x01H\x00R\x03rcs\x126\n" +
	"\x06reddit\x18\x1f \x01(\v2\x17.outbox.v1.RedditConfigB\x03\xe0A\x01H\x00R\x06reddit\x126\n" +
	"\x06signal\x18  \x01(\v2\x17.outbox.v1.SignalConfigB\x03\xe0A\x01H\x00R\x06signal\x123\n" +
	"\x05slack\x18! \x01(\v2\x16.outbox.v1.SlackConfigB\x03\xe0A\x01H\x00R\x05slack\x12-\n" +
	"\x03sms\x18\" \x01(\v2\x14.outbox.v1.SmsConfigB\x03\xe0A\x01H\x00R\x03sms\x123\n" +
	"\x05teams\x18# \x01(\v2\x16.outbox.v1.TeamsConfigB\x03\xe0A\x01H\x00R\x05teams\x12<\n" +
	"\btelegram\x18$ \x01(\v2\x19.outbox.v1.TelegramConfigB\x03\xe0A\x01H\x00R\btelegram\x129\n" +
	"\athreads\x18% \x01(\v2\x18.outbox.v1.ThreadsConfigB\x03\xe0A\x01H\x00R\athreads\x126\n" +
	"\x06tiktok\x18& \x01(\v2\x17.outbox.v1.TiktokConfigB\x03\xe0A\x01H\x00R\x06tiktok\x126\n" +
	"\x06twitch\x18' \x01(\v2\x17.outbox.v1.TwitchConfigB\x03\xe0A\x01H\x00R\x06twitch\x123\n" +
	"\x05viber\x18( \x01(\v2\x16.outbox.v1.ViberConfigB\x03\xe0A\x01H\x00R\x05viber\x123\n" +
	"\x05webex\x18) \x01(\v2\x16.outbox.v1.WebexConfigB\x03\xe0A\x01H\x00R\x05webex\x12:\n" +
	"\bweb_push\x18* \x01(\v2\x18.outbox.v1.WebPushConfigB\x03\xe0A\x01H\x00R\awebPush\x126\n" +
	"\x06wechat\x18+ \x01(\v2\x17.outbox.v1.WechatConfigB\x03\xe0A\x01H\x00R\x06wechat\x12<\n" +
	"\bwhatsapp\x18, \x01(\v2\x19.outbox.v1.WhatsAppConfigB\x03\xe0A\x01H\x00R\bwhatsapp\x12'\n" +
	"\x01x\x18- \x01(\v2\x12.outbox.v1.XConfigB\x03\xe0A\x01H\x00R\x01x\x120\n" +
	"\x04xmpp\x18. \x01(\v2\x15.outbox.v1.XmppConfigB\x03\xe0A\x01H\x00R\x04xmpp\x120\n" +
	"\x04zalo\x18/ \x01(\v2\x15.outbox.v1.ZaloConfigB\x03\xe0A\x01H\x00R\x04zalo\x129\n" +
	"\azendesk\x180 \x01(\v2\x18.outbox.v1.ZendeskConfigB\x03\xe0A\x01H\x00R\azendesk\x12=\n" +
	"\tzoom_chat\x181 \x01(\v2\x19.outbox.v1.ZoomChatConfigB\x03\xe0A\x01H\x00R\bzoomChat\"l\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTATE_ACTIVE\x10\x01\x12\x12\n" +
	"\x0eSTATE_INACTIVE\x10\x02\x12\x15\n" +
	"\x11STATE_AUTHORIZING\x10\x03\x12\x0f\n" +
	"\vSTATE_ERROR\x10\x04:I\xeaAF\n" +
	"\x15outbox.chat/Connector\x12\x16connectors/{connector}*\n" +
	"connectors2\tconnectorB\x17\n" +
	"\x0echannel_config\x12\x05\xbaH\x02\b\x01\"\x8e\x01\n" +
	"\x16CreateConnectorRequest\x12=\n" +
	"\tconnector\x18\x01 \x01(\v2\x14.outbox.v1.ConnectorB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\tconnector\x125\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tB\x16\xe0A\x01\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01\xe2\x8c\xcf\xd7\b\x02\b\x01R\trequestId\"\x84\x01\n" +
	"\x17CreateConnectorResponse\x127\n" +
	"\tconnector\x18\x01 \x01(\v2\x14.outbox.v1.ConnectorB\x03\xe0A\x03R\tconnector\x120\n" +
	"\x11authorization_url\x18\x02 \x01(\tB\x03\xe0A\x03R\x10authorizationUrl\"O\n" +
	"\x13GetConnectorRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x17\n" +
	"\x15outbox.chat/Connector\xbaH\x04r\x02\x10\x01R\x04name\"O\n" +
	"\x14GetConnectorResponse\x127\n" +
	"\tconnector\x18\x01 \x01(\v2\x14.outbox.v1.ConnectorB\x03\xe0A\x03R\tconnector\"\xa4\x01\n" +
	"\x15ListConnectorsRequest\x12*\n" +
	"\tpage_size\x18\x01 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x03 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x04 \x01(\tB\x03\xe0A\x01R\aorderBy\"\xa4\x01\n" +
	"\x16ListConnectorsResponse\x129\n" +
	"\n" +
	"connectors\x18\x01 \x03(\v2\x14.outbox.v1.ConnectorB\x03\xe0A\x03R\n" +
	"connectors\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x03\xe0A\x03R\rnextPageToken\x12\"\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05B\x03\xe0A\x03R\ttotalSize\"\x99\x01\n" +
	"\x16UpdateConnectorRequest\x12=\n" +
	"\tconnector\x18\x01 \x01(\v2\x14.outbox.v1.ConnectorB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\tconnector\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask\"R\n" +
	"\x17UpdateConnectorResponse\x127\n" +
	"\tconnector\x18\x01 \x01(\v2\x14.outbox.v1.ConnectorB\x03\xe0A\x03R\tconnector\"R\n" +
	"\x16DeleteConnectorRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x17\n" +
	"\x15outbox.chat/Connector\xbaH\x04r\x02\x10\x01R\x04name\"\x19\n" +
	"\x17DeleteConnectorResponse\"T\n" +
	"\x18ActivateConnectorRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x17\n" +
	"\x15outbox.chat/Connector\xbaH\x04r\x02\x10\x01R\x04name\"T\n" +
	"\x19ActivateConnectorResponse\x127\n" +
	"\tconnector\x18\x01 \x01(\v2\x14.outbox.v1.ConnectorB\x03\xe0A\x03R\tconnector\"V\n" +
	"\x1aDeactivateConnectorRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x17\n" +
	"\x15outbox.chat/Connector\xbaH\x04r\x02\x10\x01R\x04name\"V\n" +
	"\x1bDeactivateConnectorResponse\x127\n" +
	"\tconnector\x18\x01 \x01(\v2\x14.outbox.v1.ConnectorB\x03\xe0A\x03R\tconnector\"W\n" +
	"\x1bReauthorizeConnectorRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x17\n" +
	"\x15outbox.chat/Connector\xbaH\x04r\x02\x10\x01R\x04name\"P\n" +
	"\x1cReauthorizeConnectorResponse\x120\n" +
	"\x11authorization_url\x18\x01 \x01(\tB\x03\xe0A\x03R\x10authorizationUrl2\xd1\x06\n" +
	"\x10ConnectorService\x12f\n" +
	"\x0fCreateConnector\x12!.outbox.v1.CreateConnectorRequest\x1a\".outbox.v1.CreateConnectorResponse\"\f\xdaA\tconnector\x12X\n" +
	"\fGetConnector\x12\x1e.outbox.v1.GetConnectorRequest\x1a\x1f.outbox.v1.GetConnectorResponse\"\a\xdaA\x04name\x12Z\n" +
	"\x0eListConnectors\x12 .outbox.v1.ListConnectorsRequest\x1a!.outbox.v1.ListConnectorsResponse\"\x03\xdaA\x00\x12r\n" +
	"\x0fUpdateConnector\x12!.outbox.v1.UpdateConnectorRequest\x1a\".outbox.v1.UpdateConnectorResponse\"\x18\xdaA\x15connector,update_mask\x12a\n" +
	"\x0fDeleteConnector\x12!.outbox.v1.DeleteConnectorRequest\x1a\".outbox.v1.DeleteConnectorResponse\"\a\xdaA\x04name\x12p\n" +
	"\x14ReauthorizeConnector\x12&.outbox.v1.ReauthorizeConnectorRequest\x1a'.outbox.v1.ReauthorizeConnectorResponse\"\a\xdaA\x04name\x12g\n" +
	"\x11ActivateConnector\x12#.outbox.v1.ActivateConnectorRequest\x1a$.outbox.v1.ActivateConnectorResponse\"\a\xdaA\x04name\x12m\n" +
	"\x13DeactivateConnector\x12%.outbox.v1.DeactivateConnectorRequest\x1a&.outbox.v1.DeactivateConnectorResponse\"\a\xdaA\x04nameBPZIgithub.com/getoutbox/outbox-internal/go/outbox-api/gen/outbox/v1;outboxv1\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_outbox_v1_connector_proto_rawDescOnce sync.Once
	file_outbox_v1_connector_proto_rawDescData []byte
)

func file_outbox_v1_connector_proto_rawDescGZIP() []byte {
	file_outbox_v1_connector_proto_rawDescOnce.Do(func() {
		file_outbox_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outbox_v1_connector_proto_rawDesc), len(file_outbox_v1_connector_proto_rawDesc)))
	})
	return file_outbox_v1_connector_proto_rawDescData
}

var file_outbox_v1_connector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_outbox_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_outbox_v1_connector_proto_goTypes = []any{
	(Connector_State)(0),                 // 0: outbox.v1.Connector.State
	(*Connector)(nil),                    // 1: outbox.v1.Connector
	(*CreateConnectorRequest)(nil),       // 2: outbox.v1.CreateConnectorRequest
	(*CreateConnectorResponse)(nil),      // 3: outbox.v1.CreateConnectorResponse
	(*GetConnectorRequest)(nil),          // 4: outbox.v1.GetConnectorRequest
	(*GetConnectorResponse)(nil),         // 5: outbox.v1.GetConnectorResponse
	(*ListConnectorsRequest)(nil),        // 6: outbox.v1.ListConnectorsRequest
	(*ListConnectorsResponse)(nil),       // 7: outbox.v1.ListConnectorsResponse
	(*UpdateConnectorRequest)(nil),       // 8: outbox.v1.UpdateConnectorRequest
	(*UpdateConnectorResponse)(nil),      // 9: outbox.v1.UpdateConnectorResponse
	(*DeleteConnectorRequest)(nil),       // 10: outbox.v1.DeleteConnectorRequest
	(*DeleteConnectorResponse)(nil),      // 11: outbox.v1.DeleteConnectorResponse
	(*ActivateConnectorRequest)(nil),     // 12: outbox.v1.ActivateConnectorRequest
	(*ActivateConnectorResponse)(nil),    // 13: outbox.v1.ActivateConnectorResponse
	(*DeactivateConnectorRequest)(nil),   // 14: outbox.v1.DeactivateConnectorRequest
	(*DeactivateConnectorResponse)(nil),  // 15: outbox.v1.DeactivateConnectorResponse
	(*ReauthorizeConnectorRequest)(nil),  // 16: outbox.v1.ReauthorizeConnectorRequest
	(*ReauthorizeConnectorResponse)(nil), // 17: outbox.v1.ReauthorizeConnectorResponse
	(*Account)(nil),                      // 18: outbox.v1.Account
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
	(*ActivityPubConfig)(nil),            // 20: outbox.v1.ActivityPubConfig
	(*ApnsConfig)(nil),                   // 21: outbox.v1.ApnsConfig
	(*AppleMessagesConfig)(nil),          // 22: outbox.v1.AppleMessagesConfig
	(*BlueskyConfig)(nil),                // 23: outbox.v1.BlueskyConfig
	(*DiscordConfig)(nil),                // 24: outbox.v1.DiscordConfig
	(*EmailConfig)(nil),                  // 25: outbox.v1.EmailConfig
	(*FcmConfig)(nil),                    // 26: outbox.v1.FcmConfig
	(*FreshchatConfig)(nil),              // 27: outbox.v1.FreshchatConfig
	(*GoogleChatConfig)(nil),             // 28: outbox.v1.GoogleChatConfig
	(*HubspotConfig)(nil),                // 29: outbox.v1.HubspotConfig
	(*InAppConfig)(nil),                  // 30: outbox.v1.InAppConfig
	(*InstagramConfig)(nil),              // 31: outbox.v1.InstagramConfig
	(*IntercomConfig)(nil),               // 32: outbox.v1.IntercomConfig
	(*KakaoTalkConfig)(nil),              // 33: outbox.v1.KakaoTalkConfig
	(*LarkConfig)(nil),                   // 34: outbox.v1.LarkConfig
	(*LineConfig)(nil),                   // 35: outbox.v1.LineConfig
	(*LinkedinConfig)(nil),               // 36: outbox.v1.LinkedinConfig
	(*LiveChatConfig)(nil),               // 37: outbox.v1.LiveChatConfig
	(*MatrixConfig)(nil),                 // 38: outbox.v1.MatrixConfig
	(*MattermostConfig)(nil),             // 39: outbox.v1.MattermostConfig
	(*MessengerConfig)(nil),              // 40: outbox.v1.MessengerConfig
	(*MqttConfig)(nil),                   // 41: outbox.v1.MqttConfig
	(*RcsConfig)(nil),                    // 42: outbox.v1.RcsConfig
	(*RedditConfig)(nil),                 // 43: outbox.v1.RedditConfig
	(*SignalConfig)(nil),                 // 44: outbox.v1.SignalConfig
	(*SlackConfig)(nil),                  // 45: outbox.v1.SlackConfig
	(*SmsConfig)(nil),                    // 46: outbox.v1.SmsConfig
	(*TeamsConfig)(nil),                  // 47: outbox.v1.TeamsConfig
	(*TelegramConfig)(nil),               // 48: outbox.v1.TelegramConfig
	(*ThreadsConfig)(nil),                // 49: outbox.v1.ThreadsConfig
	(*TiktokConfig)(nil),                 // 50: outbox.v1.TiktokConfig
	(*TwitchConfig)(nil),                 // 51: outbox.v1.TwitchConfig
	(*ViberConfig)(nil),                  // 52: outbox.v1.ViberConfig
	(*WebexConfig)(nil),                  // 53: outbox.v1.WebexConfig
	(*WebPushConfig)(nil),                // 54: outbox.v1.WebPushConfig
	(*WechatConfig)(nil),                 // 55: outbox.v1.WechatConfig
	(*WhatsAppConfig)(nil),               // 56: outbox.v1.WhatsAppConfig
	(*XConfig)(nil),                      // 57: outbox.v1.XConfig
	(*XmppConfig)(nil),                   // 58: outbox.v1.XmppConfig
	(*ZaloConfig)(nil),                   // 59: outbox.v1.ZaloConfig
	(*ZendeskConfig)(nil),                // 60: outbox.v1.ZendeskConfig
	(*ZoomChatConfig)(nil),               // 61: outbox.v1.ZoomChatConfig
	(*fieldmaskpb.FieldMask)(nil),        // 62: google.protobuf.FieldMask
}
var file_outbox_v1_connector_proto_depIdxs = []int32{
	18, // 0: outbox.v1.Connector.account:type_name -> outbox.v1.Account
	0,  // 1: outbox.v1.Connector.state:type_name -> outbox.v1.Connector.State
	19, // 2: outbox.v1.Connector.create_time:type_name -> google.protobuf.Timestamp
	19, // 3: outbox.v1.Connector.update_time:type_name -> google.protobuf.Timestamp
	20, // 4: outbox.v1.Connector.activity_pub:type_name -> outbox.v1.ActivityPubConfig
	21, // 5: outbox.v1.Connector.apns:type_name -> outbox.v1.ApnsConfig
	22, // 6: outbox.v1.Connector.apple_messages:type_name -> outbox.v1.AppleMessagesConfig
	23, // 7: outbox.v1.Connector.bluesky:type_name -> outbox.v1.BlueskyConfig
	24, // 8: outbox.v1.Connector.discord:type_name -> outbox.v1.DiscordConfig
	25, // 9: outbox.v1.Connector.email:type_name -> outbox.v1.EmailConfig
	26, // 10: outbox.v1.Connector.fcm:type_name -> outbox.v1.FcmConfig
	27, // 11: outbox.v1.Connector.freshchat:type_name -> outbox.v1.FreshchatConfig
	28, // 12: outbox.v1.Connector.google_chat:type_name -> outbox.v1.GoogleChatConfig
	29, // 13: outbox.v1.Connector.hubspot:type_name -> outbox.v1.HubspotConfig
	30, // 14: outbox.v1.Connector.in_app:type_name -> outbox.v1.InAppConfig
	31, // 15: outbox.v1.Connector.instagram:type_name -> outbox.v1.InstagramConfig
	32, // 16: outbox.v1.Connector.intercom:type_name -> outbox.v1.IntercomConfig
	33, // 17: outbox.v1.Connector.kakao_talk:type_name -> outbox.v1.KakaoTalkConfig
	34, // 18: outbox.v1.Connector.lark:type_name -> outbox.v1.LarkConfig
	35, // 19: outbox.v1.Connector.line:type_name -> outbox.v1.LineConfig
	36, // 20: outbox.v1.Connector.linkedin:type_name -> outbox.v1.LinkedinConfig
	37, // 21: outbox.v1.Connector.live_chat:type_name -> outbox.v1.LiveChatConfig
	38, // 22: outbox.v1.Connector.matrix:type_name -> outbox.v1.MatrixConfig
	39, // 23: outbox.v1.Connector.mattermost:type_name -> outbox.v1.MattermostConfig
	40, // 24: outbox.v1.Connector.messenger:type_name -> outbox.v1.MessengerConfig
	41, // 25: outbox.v1.Connector.mqtt:type_name -> outbox.v1.MqttConfig
	42, // 26: outbox.v1.Connector.rcs:type_name -> outbox.v1.RcsConfig
	43, // 27: outbox.v1.Connector.reddit:type_name -> outbox.v1.RedditConfig
	44, // 28: outbox.v1.Connector.signal:type_name -> outbox.v1.SignalConfig
	45, // 29: outbox.v1.Connector.slack:type_name -> outbox.v1.SlackConfig
	46, // 30: outbox.v1.Connector.sms:type_name -> outbox.v1.SmsConfig
	47, // 31: outbox.v1.Connector.teams:type_name -> outbox.v1.TeamsConfig
	48, // 32: outbox.v1.Connector.telegram:type_name -> outbox.v1.TelegramConfig
	49, // 33: outbox.v1.Connector.threads:type_name -> outbox.v1.ThreadsConfig
	50, // 34: outbox.v1.Connector.tiktok:type_name -> outbox.v1.TiktokConfig
	51, // 35: outbox.v1.Connector.twitch:type_name -> outbox.v1.TwitchConfig
	52, // 36: outbox.v1.Connector.viber:type_name -> outbox.v1.ViberConfig
	53, // 37: outbox.v1.Connector.webex:type_name -> outbox.v1.WebexConfig
	54, // 38: outbox.v1.Connector.web_push:type_name -> outbox.v1.WebPushConfig
	55, // 39: outbox.v1.Connector.wechat:type_name -> outbox.v1.WechatConfig
	56, // 40: outbox.v1.Connector.whatsapp:type_name -> outbox.v1.WhatsAppConfig
	57, // 41: outbox.v1.Connector.x:type_name -> outbox.v1.XConfig
	58, // 42: outbox.v1.Connector.xmpp:type_name -> outbox.v1.XmppConfig
	59, // 43: outbox.v1.Connector.zalo:type_name -> outbox.v1.ZaloConfig
	60, // 44: outbox.v1.Connector.zendesk:type_name -> outbox.v1.ZendeskConfig
	61, // 45: outbox.v1.Connector.zoom_chat:type_name -> outbox.v1.ZoomChatConfig
	1,  // 46: outbox.v1.CreateConnectorRequest.connector:type_name -> outbox.v1.Connector
	1,  // 47: outbox.v1.CreateConnectorResponse.connector:type_name -> outbox.v1.Connector
	1,  // 48: outbox.v1.GetConnectorResponse.connector:type_name -> outbox.v1.Connector
	1,  // 49: outbox.v1.ListConnectorsResponse.connectors:type_name -> outbox.v1.Connector
	1,  // 50: outbox.v1.UpdateConnectorRequest.connector:type_name -> outbox.v1.Connector
	62, // 51: outbox.v1.UpdateConnectorRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 52: outbox.v1.UpdateConnectorResponse.connector:type_name -> outbox.v1.Connector
	1,  // 53: outbox.v1.ActivateConnectorResponse.connector:type_name -> outbox.v1.Connector
	1,  // 54: outbox.v1.DeactivateConnectorResponse.connector:type_name -> outbox.v1.Connector
	2,  // 55: outbox.v1.ConnectorService.CreateConnector:input_type -> outbox.v1.CreateConnectorRequest
	4,  // 56: outbox.v1.ConnectorService.GetConnector:input_type -> outbox.v1.GetConnectorRequest
	6,  // 57: outbox.v1.ConnectorService.ListConnectors:input_type -> outbox.v1.ListConnectorsRequest
	8,  // 58: outbox.v1.ConnectorService.UpdateConnector:input_type -> outbox.v1.UpdateConnectorRequest
	10, // 59: outbox.v1.ConnectorService.DeleteConnector:input_type -> outbox.v1.DeleteConnectorRequest
	16, // 60: outbox.v1.ConnectorService.ReauthorizeConnector:input_type -> outbox.v1.ReauthorizeConnectorRequest
	12, // 61: outbox.v1.ConnectorService.ActivateConnector:input_type -> outbox.v1.ActivateConnectorRequest
	14, // 62: outbox.v1.ConnectorService.DeactivateConnector:input_type -> outbox.v1.DeactivateConnectorRequest
	3,  // 63: outbox.v1.ConnectorService.CreateConnector:output_type -> outbox.v1.CreateConnectorResponse
	5,  // 64: outbox.v1.ConnectorService.GetConnector:output_type -> outbox.v1.GetConnectorResponse
	7,  // 65: outbox.v1.ConnectorService.ListConnectors:output_type -> outbox.v1.ListConnectorsResponse
	9,  // 66: outbox.v1.ConnectorService.UpdateConnector:output_type -> outbox.v1.UpdateConnectorResponse
	11, // 67: outbox.v1.ConnectorService.DeleteConnector:output_type -> outbox.v1.DeleteConnectorResponse
	17, // 68: outbox.v1.ConnectorService.ReauthorizeConnector:output_type -> outbox.v1.ReauthorizeConnectorResponse
	13, // 69: outbox.v1.ConnectorService.ActivateConnector:output_type -> outbox.v1.ActivateConnectorResponse
	15, // 70: outbox.v1.ConnectorService.DeactivateConnector:output_type -> outbox.v1.DeactivateConnectorResponse
	63, // [63:71] is the sub-list for method output_type
	55, // [55:63] is the sub-list for method input_type
	55, // [55:55] is the sub-list for extension type_name
	55, // [55:55] is the sub-list for extension extendee
	0,  // [0:55] is the sub-list for field type_name
}

func init() { file_outbox_v1_connector_proto_init() }
func file_outbox_v1_connector_proto_init() {
	if File_outbox_v1_connector_proto != nil {
		return
	}
	file_outbox_v1_account_proto_init()
	file_outbox_v1_connector_config_proto_init()
	file_outbox_v1_connector_proto_msgTypes[0].OneofWrappers = []any{
		(*Connector_ActivityPub)(nil),
		(*Connector_Apns)(nil),
		(*Connector_AppleMessages)(nil),
		(*Connector_Bluesky)(nil),
		(*Connector_Discord)(nil),
		(*Connector_Email)(nil),
		(*Connector_Fcm)(nil),
		(*Connector_Freshchat)(nil),
		(*Connector_GoogleChat)(nil),
		(*Connector_Hubspot)(nil),
		(*Connector_InApp)(nil),
		(*Connector_Instagram)(nil),
		(*Connector_Intercom)(nil),
		(*Connector_KakaoTalk)(nil),
		(*Connector_Lark)(nil),
		(*Connector_Line)(nil),
		(*Connector_Linkedin)(nil),
		(*Connector_LiveChat)(nil),
		(*Connector_Matrix)(nil),
		(*Connector_Mattermost)(nil),
		(*Connector_Messenger)(nil),
		(*Connector_Mqtt)(nil),
		(*Connector_Rcs)(nil),
		(*Connector_Reddit)(nil),
		(*Connector_Signal)(nil),
		(*Connector_Slack)(nil),
		(*Connector_Sms)(nil),
		(*Connector_Teams)(nil),
		(*Connector_Telegram)(nil),
		(*Connector_Threads)(nil),
		(*Connector_Tiktok)(nil),
		(*Connector_Twitch)(nil),
		(*Connector_Viber)(nil),
		(*Connector_Webex)(nil),
		(*Connector_WebPush)(nil),
		(*Connector_Wechat)(nil),
		(*Connector_Whatsapp)(nil),
		(*Connector_X)(nil),
		(*Connector_Xmpp)(nil),
		(*Connector_Zalo)(nil),
		(*Connector_Zendesk)(nil),
		(*Connector_ZoomChat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outbox_v1_connector_proto_rawDesc), len(file_outbox_v1_connector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outbox_v1_connector_proto_goTypes,
		DependencyIndexes: file_outbox_v1_connector_proto_depIdxs,
		EnumInfos:         file_outbox_v1_connector_proto_enumTypes,
		MessageInfos:      file_outbox_v1_connector_proto_msgTypes,
	}.Build()
	File_outbox_v1_connector_proto = out.File
	file_outbox_v1_connector_proto_goTypes = nil
	file_outbox_v1_connector_proto_depIdxs = nil
}
